import 'package:flutter/material.dart';

// دليل استخدام تطبيق Alerts (تنبيهات) — مفهرس، ثلاثيّ الأبعاد، متعدّد اللغات.
//
// البنية مدفوعة بالبيانات: الأيقونات والألوان وحالة الطيّ مشتركة بين كل اللغات،
// ولكل لغة قائمة نصوص مسطّحة فقط (عنوان القسم ثم عنوان/وصف لكل عنصر). هذا يقلّل
// التكرار ويُبقي 13 لغة متناسقة.
class HgItem {
  final IconData icon;
  final String title;
  final String desc;
  const HgItem(this.icon, this.title, this.desc);
}

class HgSection {
  final IconData icon;
  final Color color;
  final bool expanded;
  final String title;
  final List<HgItem> items;
  const HgSection(this.icon, this.color, this.expanded, this.title, this.items);
}

class HgChrome {
  final String subtitle;
  final String items;
  final String updated;
  const HgChrome(this.subtitle, this.items, this.updated);
}

// ألوان الأقسام الثمانية.
const _c1 = Color(0xFF5C6BC0); // البداية السريعة
const _c2 = Color(0xFF26A69A); // أنواع التنبيه
const _c3 = Color(0xFFEF6C00); // الوقت والتكرار
const _c4 = Color(0xFF42A5F5); // العرض والتنظيم
const _c5 = Color(0xFF7E57C2); // التخصيص والمرفقات
const _c6 = Color(0xFFE53935); // الصوت والإلحاح
const _c7 = Color(0xFFEC407A); // المتابعة والإحصاء
const _c8 = Color(0xFF6D4C41); // النظام والإعدادات

// أيقونة + لون + حالة الطيّ لكل قسم (مشتركة بين اللغات).
const List<IconData> _sectionIcons = [
  Icons.rocket_launch,
  Icons.category,
  Icons.event_repeat,
  Icons.volume_up,
  Icons.palette,
  Icons.dashboard_customize,
  Icons.insights,
  Icons.settings_suggest,
];
const List<Color> _sectionColors = [_c1, _c2, _c3, _c6, _c5, _c4, _c7, _c8];

// أيقونات عناصر كل قسم (مشتركة بين اللغات). أعداد العناصر:
// [5, 7, 6, 5, 6, 5, 3, 6].
const List<List<IconData>> _itemIcons = [
  [Icons.add_circle, Icons.title, Icons.schedule, Icons.check_circle, Icons.mic],
  [
    Icons.notifications_active,
    Icons.medication,
    Icons.event,
    Icons.celebration,
    Icons.receipt_long,
    Icons.flight,
    Icons.directions_car
  ],
  [
    Icons.repeat,
    Icons.mosque,
    Icons.event_repeat,
    Icons.medication_liquid,
    Icons.timer,
    Icons.snooze
  ],
  [
    Icons.library_music,
    Icons.volume_up,
    Icons.crisis_alert,
    Icons.calculate,
    Icons.alarm_on
  ],
  [
    Icons.color_lens,
    Icons.priority_high,
    Icons.mic_none,
    Icons.attach_file,
    Icons.place,
    Icons.visibility
  ],
  [
    Icons.view_agenda,
    Icons.palette_outlined,
    Icons.search,
    Icons.dashboard_customize,
    Icons.record_voice_over
  ],
  [Icons.today, Icons.bar_chart, Icons.history],
  [
    Icons.system_update,
    Icons.backup,
    Icons.cloud,
    Icons.lock,
    Icons.calendar_month,
    Icons.vpn_key
  ],
];

/// يبني أقسام الدليل من قائمة نصوص اللغة (عنوان القسم ثم عنوان/وصف لكل عنصر).
List<HgSection> _build(List<List<String>> langStrings) {
  final out = <HgSection>[];
  for (var s = 0; s < _sectionIcons.length; s++) {
    final strs = langStrings[s];
    final icons = _itemIcons[s];
    final items = <HgItem>[];
    for (var i = 0; i < icons.length; i++) {
      items.add(HgItem(icons[i], strs[1 + i * 2], strs[2 + i * 2]));
    }
    out.add(
        HgSection(_sectionIcons[s], _sectionColors[s], s == 0, strs[0], items));
  }
  return out;
}

// نصوص الدليل لكل لغة. كل لغة = 8 أقسام، وكل قسم قائمة مسطّحة:
// [عنوان القسم، عنوان1، وصف1، عنوان2، وصف2، ...].
const Map<String, List<List<String>>> _hg = {
  'en': [
    ['Quick start',
      'Tap +', 'Opens the new-reminder dialog',
      'Title', 'What to remember — or dictate it by mic',
      'Pick the time', 'Date and time, Hijri or Gregorian',
      'Save', 'Schedules instantly and shows on Home',
      'Voice add', 'Tap the mic and say: remind me to call Ahmed in an hour'],
    ['Reminder types',
      'General', 'Any everyday reminder',
      'Medication', 'Doses and a course count',
      'Appointment', 'With location and invitation',
      'Occasion', 'Birthdays and events — yearly',
      'Bills', 'Recurring payments',
      'Travel', 'Trips and departures',
      'Car', 'Service and renewals'],
    ['Time & repeat',
      'Repeat', 'Once · daily · weekly · monthly · yearly',
      'Hijri yearly', 'Repeats on the Hijri date each year',
      'Every N days', 'Your own custom interval',
      'Medication course', 'Set total doses; remaining counts down',
      'Pre-alert', '5 min / 15 min / hour / day before',
      'Snooze', '5–60 minutes from the alarm screen'],
    ['Sound & urgency',
      'Sound library', 'Built-in tones plus your device tones',
      'Auto-raise volume', 'Heard on silent or low — optional gradual ramp',
      'Escalating critical', 'Sound and vibration grow if ignored',
      'Cannot-miss mode', 'Solve a small sum before dismissing',
      'Reliable alarm', 'Fires when closed or after reboot, full-screen'],
    ['Customize & attach',
      'Custom color', 'A color per reminder, shown on its card',
      'Importance', 'Normal or critical full alarm screen',
      'Voice note', 'Attach a recording',
      'Image / PDF', 'Attach an invitation or document',
      'Location', 'Google Maps link or pick a spot',
      'Live preview', 'See the reminder as you type'],
    ['View & organize',
      'List or grid', 'Switch view — your choice is saved',
      'Color time-groups', 'Today / tomorrow / this week / later',
      'Search', 'Find any reminder fast',
      'Templates', 'Ready-made: meds, travel, car, bill…',
      'Voice creation', 'Speak a sentence; it fills the form'],
    ['Insights',
      'Today board', 'Due · critical · overdue · active + next alarm',
      'Statistics', 'Total · this week · peak hour · most frequent',
      'Notification log', 'Every fired reminder, logged automatically'],
    ['System & settings',
      'In-app update', 'Check and install new versions — no browser',
      'Backup', 'Save and restore your reminders',
      'Cloud sync', 'Encrypted Google Drive sync',
      'App lock', 'PIN or fingerprint',
      'Add to calendar', 'Export .ics or share as text',
      'Activation', 'Universal license key — activate or deactivate'],
  ],
  'ar': [
    ['البداية السريعة',
      'اضغط +', 'يفتح حوار التنبيه الجديد',
      'العنوان', 'ما تريد تذكّره — أو أملِه بالميكروفون',
      'اختر الوقت', 'تاريخ ووقت، هجريّ أو ميلاديّ',
      'حفظ', 'يُجدوَل فورًا ويظهر في الرئيسية',
      'إضافة صوتية', 'اضغط الميكروفون وقل: ذكّرني أتصل بأحمد بعد ساعة'],
    ['أنواع التنبيه',
      'عام', 'أيّ تذكير يوميّ',
      'دواء', 'جرعات وعدد كورس',
      'موعد', 'مع موقع ودعوة',
      'مناسبة', 'أعياد ومناسبات — سنويّ',
      'فواتير', 'مدفوعات متكرّرة',
      'سفر', 'رحلات ومواعيد إقلاع',
      'سيارة', 'صيانة وتجديدات'],
    ['الوقت والتكرار',
      'التكرار', 'مرّة · يوميّ · أسبوعيّ · شهريّ · سنويّ',
      'سنويّ هجريّ', 'يتكرّر في التاريخ الهجريّ كلّ عام',
      'كلّ N يوم', 'فاصل مخصّص باختيارك',
      'كورس دواء', 'حدّد عدد الجرعات؛ المتبقّي ينقص',
      'تنبيه مسبق', '5د / 15د / ساعة / يوم قبل',
      'غفوة', '5–60 دقيقة من شاشة المنبّه'],
    ['الصوت والإلحاح',
      'مكتبة الأصوات', 'نغمات مدمجة + نغمات جهازك',
      'رفع الصوت تلقائيًّا', 'يُسمَع مع الصامت/المنخفض — تدرّج اختياريّ',
      'تصعيد حرج', 'يزداد الصوت والاهتزاز إن تُجوهِل',
      'وضع لا يُفوَّت', 'احسب مسألة بسيطة قبل الإيقاف',
      'منبّه موثوق', 'يعمل والتطبيق مغلق أو بعد التشغيل، شاشة كاملة'],
    ['التخصيص والمرفقات',
      'لون مخصّص', 'لون لكلّ تنبيه يظهر على بطاقته',
      'الأهمّية', 'عاديّ أو حرج بشاشة منبّه كاملة',
      'ملاحظة صوتية', 'أرفِق تسجيلًا',
      'صورة / PDF', 'أرفِق دعوة أو مستندًا',
      'الموقع', 'رابط خرائط جوجل أو اختيار نقطة',
      'معاينة حيّة', 'شاهد التنبيه وأنت تكتبه'],
    ['العرض والتنظيم',
      'قائمة أو مربّعات', 'بدّل العرض — يُحفظ اختيارك',
      'تجميع زمنيّ ملوّن', 'اليوم / غدًا / هذا الأسبوع / لاحقًا',
      'بحث', 'اعثر على أيّ تنبيه بسرعة',
      'قوالب جاهزة', 'أدوية، سفر، سيارة، فاتورة…',
      'إنشاء صوتيّ', 'انطق جملة فيملأ النموذج'],
    ['المتابعة والإحصاء',
      'لوحة اليوم', 'قادمة · حرِجة · فائتة · نشطة + التالي',
      'إحصاءات', 'الإجمالي · هذا الأسبوع · أكثر وقت · الأكثر تكرارًا',
      'سجلّ التنبيهات', 'كلّ تنبيه يُسجَّل تلقائيًّا'],
    ['النظام والإعدادات',
      'تحديث داخليّ', 'تحقّق وثبّت النسخ الجديدة — بلا متصفّح',
      'نسخ احتياطيّ', 'احفظ واسترجع تنبيهاتك',
      'مزامنة سحابية', 'مزامنة Google Drive مشفّرة',
      'قفل التطبيق', 'رقم سرّي أو بصمة',
      'إضافة للتقويم', 'صدّر .ics أو شارك كنصّ',
      'التفعيل', 'مفتاح ترخيص عالميّ — تفعيل أو إلغاء'],
  ],
  'es': [
    ['Inicio rápido',
      'Toca +', 'Abre el diálogo de nuevo recordatorio',
      'Título', 'Qué recordar — o díctalo por micrófono',
      'Elige la hora', 'Fecha y hora, hijri o gregoriano',
      'Guardar', 'Se programa al instante y aparece en Inicio',
      'Añadir por voz', 'Toca el micrófono y di: recuérdame llamar a Ahmed en una hora'],
    ['Tipos de recordatorio',
      'General', 'Cualquier recordatorio diario',
      'Medicación', 'Dosis y recuento del tratamiento',
      'Cita', 'Con ubicación e invitación',
      'Evento', 'Cumpleaños y eventos — anual',
      'Facturas', 'Pagos recurrentes',
      'Viaje', 'Viajes y salidas',
      'Coche', 'Mantenimiento y renovaciones'],
    ['Hora y repetición',
      'Repetir', 'Una vez · diario · semanal · mensual · anual',
      'Anual hijri', 'Se repite en la fecha hijri cada año',
      'Cada N días', 'Tu propio intervalo personalizado',
      'Tratamiento', 'Fija las dosis totales; lo restante baja',
      'Aviso previo', '5 min / 15 min / hora / día antes',
      'Posponer', '5–60 minutos desde la pantalla de alarma'],
    ['Sonido y urgencia',
      'Biblioteca de sonidos', 'Tonos integrados más los del dispositivo',
      'Subir volumen', 'Se oye en silencio o bajo — subida gradual opcional',
      'Crítico creciente', 'El sonido y la vibración crecen si se ignora',
      'Modo imperdible', 'Resuelve una suma simple antes de descartar',
      'Alarma fiable', 'Suena cerrada o tras reiniciar, pantalla completa'],
    ['Personalizar y adjuntar',
      'Color propio', 'Un color por recordatorio, visible en su tarjeta',
      'Importancia', 'Normal o crítico con alarma a pantalla completa',
      'Nota de voz', 'Adjunta una grabación',
      'Imagen / PDF', 'Adjunta una invitación o documento',
      'Ubicación', 'Enlace de Google Maps o elige un punto',
      'Vista previa', 'Ve el recordatorio mientras escribes'],
    ['Ver y organizar',
      'Lista o cuadrícula', 'Cambia la vista — se guarda tu elección',
      'Grupos por tiempo', 'Hoy / mañana / esta semana / después',
      'Buscar', 'Encuentra cualquier recordatorio rápido',
      'Plantillas', 'Listas: medicación, viaje, coche, factura…',
      'Crear por voz', 'Di una frase y rellena el formulario'],
    ['Análisis',
      'Panel de hoy', 'Pendiente · crítico · vencido · activo + próximo',
      'Estadísticas', 'Total · esta semana · hora pico · más frecuente',
      'Registro de avisos', 'Cada recordatorio disparado se registra solo'],
    ['Sistema y ajustes',
      'Actualización integrada', 'Busca e instala nuevas versiones — sin navegador',
      'Copia de seguridad', 'Guarda y restaura tus recordatorios',
      'Sync en la nube', 'Sincronización cifrada con Google Drive',
      'Bloqueo de app', 'PIN o huella',
      'Añadir al calendario', 'Exporta .ics o comparte como texto',
      'Activación', 'Clave de licencia universal — activar o desactivar'],
  ],
  'de': [
    ['Schnellstart',
      'Auf + tippen', 'Öffnet den Dialog für neue Erinnerung',
      'Titel', 'Woran erinnern — oder per Mikrofon diktieren',
      'Zeit wählen', 'Datum und Uhrzeit, Hidschri oder gregorianisch',
      'Speichern', 'Wird sofort geplant und auf Start angezeigt',
      'Per Sprache', 'Mikrofon tippen und sagen: erinnere mich in einer Stunde Ahmed anzurufen'],
    ['Erinnerungstypen',
      'Allgemein', 'Jede alltägliche Erinnerung',
      'Medikament', 'Dosen und Kur-Zählung',
      'Termin', 'Mit Ort und Einladung',
      'Anlass', 'Geburtstage und Anlässe — jährlich',
      'Rechnungen', 'Wiederkehrende Zahlungen',
      'Reise', 'Reisen und Abflüge',
      'Auto', 'Wartung und Verlängerungen'],
    ['Zeit & Wiederholung',
      'Wiederholen', 'Einmal · täglich · wöchentlich · monatlich · jährlich',
      'Jährlich Hidschri', 'Wiederholt sich jährlich am Hidschri-Datum',
      'Alle N Tage', 'Dein eigenes Intervall',
      'Medikamenten-Kur', 'Gesamtdosen festlegen; Rest zählt herunter',
      'Vorab-Hinweis', '5 Min / 15 Min / Stunde / Tag vorher',
      'Schlummern', '5–60 Minuten vom Wecker-Bildschirm'],
    ['Ton & Dringlichkeit',
      'Klangbibliothek', 'Integrierte Töne plus Gerätetöne',
      'Lautstärke anheben', 'Hörbar bei lautlos/leise — optional schrittweise',
      'Steigende Dringlichkeit', 'Ton und Vibration wachsen bei Ignorieren',
      'Unverpassbar-Modus', 'Eine kleine Summe lösen vor dem Beenden',
      'Zuverlässiger Wecker', 'Auch geschlossen oder nach Neustart, Vollbild'],
    ['Anpassen & anhängen',
      'Eigene Farbe', 'Eine Farbe je Erinnerung, auf der Karte sichtbar',
      'Wichtigkeit', 'Normal oder kritisch mit Vollbild-Wecker',
      'Sprachnotiz', 'Eine Aufnahme anhängen',
      'Bild / PDF', 'Einladung oder Dokument anhängen',
      'Ort', 'Google-Maps-Link oder Punkt wählen',
      'Live-Vorschau', 'Erinnerung beim Tippen sehen'],
    ['Ansicht & Organisation',
      'Liste oder Raster', 'Ansicht wechseln — Auswahl wird gespeichert',
      'Farbige Zeitgruppen', 'Heute / morgen / diese Woche / später',
      'Suche', 'Jede Erinnerung schnell finden',
      'Vorlagen', 'Fertig: Medikament, Reise, Auto, Rechnung…',
      'Per Sprache erstellen', 'Einen Satz sprechen, füllt das Formular'],
    ['Einblicke',
      'Heute-Übersicht', 'Fällig · kritisch · überfällig · aktiv + nächster',
      'Statistik', 'Gesamt · diese Woche · Stoßzeit · häufigster',
      'Mitteilungsprotokoll', 'Jede ausgelöste Erinnerung automatisch erfasst'],
    ['System & Einstellungen',
      'In-App-Update', 'Neue Versionen prüfen und installieren — ohne Browser',
      'Sicherung', 'Erinnerungen speichern und wiederherstellen',
      'Cloud-Sync', 'Verschlüsselte Google-Drive-Sync',
      'App-Sperre', 'PIN oder Fingerabdruck',
      'Zum Kalender', '.ics exportieren oder als Text teilen',
      'Aktivierung', 'Universeller Lizenzschlüssel — aktivieren oder deaktivieren'],
  ],
  'fr': [
    ['Démarrage rapide',
      'Touchez +', 'Ouvre la boîte de nouveau rappel',
      'Titre', 'Quoi retenir — ou dictez-le au micro',
      'Choisir l’heure', 'Date et heure, hégirien ou grégorien',
      'Enregistrer', 'Programmé aussitôt et affiché à l’Accueil',
      'Ajout vocal', 'Touchez le micro et dites : rappelle-moi d’appeler Ahmed dans une heure'],
    ['Types de rappel',
      'Général', 'Tout rappel du quotidien',
      'Médicament', 'Doses et décompte de la cure',
      'Rendez-vous', 'Avec lieu et invitation',
      'Occasion', 'Anniversaires et événements — annuel',
      'Factures', 'Paiements récurrents',
      'Voyage', 'Voyages et départs',
      'Voiture', 'Entretien et renouvellements'],
    ['Heure et répétition',
      'Répéter', 'Une fois · quotidien · hebdo · mensuel · annuel',
      'Annuel hégirien', 'Se répète à la date hégirienne chaque année',
      'Tous les N jours', 'Votre intervalle personnalisé',
      'Cure de médicament', 'Définir le total ; le reste décompte',
      'Pré-alerte', '5 min / 15 min / heure / jour avant',
      'Répéter l’alarme', '5–60 minutes depuis l’écran d’alarme'],
    ['Son et urgence',
      'Bibliothèque de sons', 'Sonneries intégrées plus celles de l’appareil',
      'Monter le volume', 'Audible en silencieux ou bas — montée progressive',
      'Critique croissant', 'Le son et la vibration montent si ignoré',
      'Mode incontournable', 'Résoudre une petite somme avant de fermer',
      'Alarme fiable', 'Sonne fermée ou après redémarrage, plein écran'],
    ['Personnaliser et joindre',
      'Couleur propre', 'Une couleur par rappel, visible sur la carte',
      'Importance', 'Normal ou critique en alarme plein écran',
      'Note vocale', 'Joindre un enregistrement',
      'Image / PDF', 'Joindre une invitation ou un document',
      'Lieu', 'Lien Google Maps ou choisir un point',
      'Aperçu en direct', 'Voir le rappel pendant la saisie'],
    ['Affichage et organisation',
      'Liste ou grille', 'Changer la vue — votre choix est gardé',
      'Groupes par temps', 'Aujourd’hui / demain / cette semaine / plus tard',
      'Recherche', 'Trouver vite n’importe quel rappel',
      'Modèles', 'Prêts : médicament, voyage, voiture, facture…',
      'Création vocale', 'Dites une phrase, elle remplit le formulaire'],
    ['Aperçus',
      'Tableau du jour', 'À faire · critique · en retard · actif + prochain',
      'Statistiques', 'Total · cette semaine · heure de pointe · plus fréquent',
      'Journal des alertes', 'Chaque rappel déclenché est consigné'],
    ['Système et réglages',
      'Mise à jour intégrée', 'Vérifier et installer les nouvelles versions — sans navigateur',
      'Sauvegarde', 'Enregistrer et restaurer vos rappels',
      'Sync cloud', 'Sync chiffrée Google Drive',
      'Verrou de l’app', 'PIN ou empreinte',
      'Au calendrier', 'Exporter .ics ou partager en texte',
      'Activation', 'Clé de licence universelle — activer ou désactiver'],
  ],
  'it': [
    ['Avvio rapido',
      'Tocca +', 'Apre la finestra del nuovo promemoria',
      'Titolo', 'Cosa ricordare — o dettalo al microfono',
      'Scegli l’ora', 'Data e ora, hijri o gregoriano',
      'Salva', 'Programmato subito e mostrato in Home',
      'Aggiunta vocale', 'Tocca il microfono e di’: ricordami di chiamare Ahmed tra un’ora'],
    ['Tipi di promemoria',
      'Generale', 'Qualsiasi promemoria quotidiano',
      'Farmaco', 'Dosi e conteggio del ciclo',
      'Appuntamento', 'Con luogo e invito',
      'Occasione', 'Compleanni ed eventi — annuale',
      'Bollette', 'Pagamenti ricorrenti',
      'Viaggio', 'Viaggi e partenze',
      'Auto', 'Manutenzione e rinnovi'],
    ['Ora e ripetizione',
      'Ripeti', 'Una volta · giornaliero · settimanale · mensile · annuale',
      'Annuale hijri', 'Si ripete alla data hijri ogni anno',
      'Ogni N giorni', 'Il tuo intervallo personalizzato',
      'Ciclo di farmaco', 'Imposta le dosi totali; il resto cala',
      'Pre-avviso', '5 min / 15 min / ora / giorno prima',
      'Posponi', '5–60 minuti dalla schermata di sveglia'],
    ['Suono e urgenza',
      'Libreria suoni', 'Toni integrati più quelli del dispositivo',
      'Alza il volume', 'Udibile in silenzioso o basso — salita graduale',
      'Critico crescente', 'Suono e vibrazione crescono se ignorato',
      'Modalità irrinunciabile', 'Risolvi una somma prima di chiudere',
      'Sveglia affidabile', 'Suona chiusa o dopo riavvio, schermo intero'],
    ['Personalizza e allega',
      'Colore proprio', 'Un colore per promemoria, sulla scheda',
      'Importanza', 'Normale o critico con sveglia a schermo intero',
      'Nota vocale', 'Allega una registrazione',
      'Immagine / PDF', 'Allega un invito o un documento',
      'Luogo', 'Link Google Maps o scegli un punto',
      'Anteprima dal vivo', 'Vedi il promemoria mentre scrivi'],
    ['Vista e organizzazione',
      'Elenco o griglia', 'Cambia vista — la scelta è salvata',
      'Gruppi per tempo', 'Oggi / domani / questa settimana / dopo',
      'Cerca', 'Trova subito qualsiasi promemoria',
      'Modelli', 'Pronti: farmaco, viaggio, auto, bolletta…',
      'Creazione vocale', 'Di’ una frase, compila il modulo'],
    ['Approfondimenti',
      'Pannello di oggi', 'In scadenza · critico · scaduto · attivo + prossimo',
      'Statistiche', 'Totale · questa settimana · ora di punta · più frequente',
      'Registro avvisi', 'Ogni promemoria attivato registrato in automatico'],
    ['Sistema e impostazioni',
      'Aggiornamento in-app', 'Cerca e installa nuove versioni — senza browser',
      'Backup', 'Salva e ripristina i promemoria',
      'Sync nel cloud', 'Sync crittografata con Google Drive',
      'Blocco app', 'PIN o impronta',
      'Al calendario', 'Esporta .ics o condividi come testo',
      'Attivazione', 'Chiave di licenza universale — attiva o disattiva'],
  ],
  'id': [
    ['Mulai cepat',
      'Ketuk +', 'Membuka dialog pengingat baru',
      'Judul', 'Apa yang diingat — atau diktekan lewat mik',
      'Pilih waktu', 'Tanggal dan jam, Hijriah atau Masehi',
      'Simpan', 'Langsung dijadwalkan dan tampil di Beranda',
      'Tambah suara', 'Ketuk mik dan ucapkan: ingatkan saya menelepon Ahmed satu jam lagi'],
    ['Jenis pengingat',
      'Umum', 'Pengingat harian apa pun',
      'Obat', 'Dosis dan hitungan kursus',
      'Janji temu', 'Dengan lokasi dan undangan',
      'Acara', 'Ulang tahun dan acara — tahunan',
      'Tagihan', 'Pembayaran berulang',
      'Perjalanan', 'Perjalanan dan keberangkatan',
      'Mobil', 'Servis dan perpanjangan'],
    ['Waktu & ulang',
      'Ulangi', 'Sekali · harian · mingguan · bulanan · tahunan',
      'Tahunan Hijriah', 'Berulang pada tanggal Hijriah tiap tahun',
      'Tiap N hari', 'Interval kustom Anda',
      'Kursus obat', 'Tetapkan total dosis; sisa berkurang',
      'Pra-peringatan', '5 mnt / 15 mnt / jam / hari sebelum',
      'Tunda', '5–60 menit dari layar alarm'],
    ['Suara & urgensi',
      'Pustaka suara', 'Nada bawaan plus nada perangkat',
      'Naikkan volume', 'Terdengar saat senyap/pelan — naik bertahap',
      'Kritis menanjak', 'Suara dan getaran naik bila diabaikan',
      'Mode tak terlewat', 'Selesaikan hitungan kecil sebelum menutup',
      'Alarm andal', 'Berbunyi saat tertutup atau usai restart, layar penuh'],
    ['Sesuaikan & lampirkan',
      'Warna sendiri', 'Satu warna per pengingat, tampil di kartu',
      'Kepentingan', 'Normal atau kritis dengan alarm layar penuh',
      'Catatan suara', 'Lampirkan rekaman',
      'Gambar / PDF', 'Lampirkan undangan atau dokumen',
      'Lokasi', 'Tautan Google Maps atau pilih titik',
      'Pratinjau langsung', 'Lihat pengingat saat mengetik'],
    ['Tampil & atur',
      'Daftar atau kisi', 'Ganti tampilan — pilihan tersimpan',
      'Grup waktu berwarna', 'Hari ini / besok / minggu ini / nanti',
      'Cari', 'Temukan pengingat dengan cepat',
      'Templat', 'Siap: obat, perjalanan, mobil, tagihan…',
      'Buat dengan suara', 'Ucapkan kalimat, formulir terisi'],
    ['Wawasan',
      'Papan hari ini', 'Jatuh tempo · kritis · lewat · aktif + berikutnya',
      'Statistik', 'Total · minggu ini · jam puncak · paling sering',
      'Log notifikasi', 'Tiap pengingat berbunyi dicatat otomatis'],
    ['Sistem & setelan',
      'Pembaruan dalam aplikasi', 'Periksa dan pasang versi baru — tanpa peramban',
      'Cadangan', 'Simpan dan pulihkan pengingat',
      'Sinkron awan', 'Sinkron Google Drive terenkripsi',
      'Kunci aplikasi', 'PIN atau sidik jari',
      'Ke kalender', 'Ekspor .ics atau bagikan sebagai teks',
      'Aktivasi', 'Kunci lisensi universal — aktifkan atau nonaktifkan'],
  ],
  'ms': [
    ['Mula pantas',
      'Ketik +', 'Membuka dialog peringatan baharu',
      'Tajuk', 'Apa yang diingat — atau sebut melalui mik',
      'Pilih masa', 'Tarikh dan masa, Hijrah atau Masihi',
      'Simpan', 'Dijadualkan serta-merta dan dipapar di Utama',
      'Tambah suara', 'Ketik mik dan sebut: ingatkan saya telefon Ahmed sejam lagi'],
    ['Jenis peringatan',
      'Umum', 'Sebarang peringatan harian',
      'Ubat', 'Dos dan kiraan kursus',
      'Temu janji', 'Dengan lokasi dan jemputan',
      'Majlis', 'Hari lahir dan majlis — tahunan',
      'Bil', 'Bayaran berulang',
      'Perjalanan', 'Perjalanan dan pelepasan',
      'Kereta', 'Servis dan pembaharuan'],
    ['Masa & ulang',
      'Ulang', 'Sekali · harian · mingguan · bulanan · tahunan',
      'Tahunan Hijrah', 'Berulang pada tarikh Hijrah setiap tahun',
      'Setiap N hari', 'Selang tersuai anda',
      'Kursus ubat', 'Tetapkan jumlah dos; baki berkurang',
      'Pra-amaran', '5 min / 15 min / jam / hari sebelum',
      'Tunda', '5–60 minit dari skrin penggera'],
    ['Bunyi & desakan',
      'Pustaka bunyi', 'Nada terbina serta nada peranti',
      'Naikkan kelantangan', 'Didengar ketika senyap/perlahan — naik beransur',
      'Kritikal menaik', 'Bunyi dan getaran naik jika diabaikan',
      'Mod tak terlepas', 'Selesaikan kiraan kecil sebelum menutup',
      'Penggera boleh harap', 'Berbunyi ditutup atau selepas but, skrin penuh'],
    ['Sesuaikan & lampir',
      'Warna sendiri', 'Satu warna setiap peringatan, pada kad',
      'Kepentingan', 'Biasa atau kritikal dengan penggera skrin penuh',
      'Nota suara', 'Lampirkan rakaman',
      'Imej / PDF', 'Lampirkan jemputan atau dokumen',
      'Lokasi', 'Pautan Google Maps atau pilih titik',
      'Pratonton langsung', 'Lihat peringatan sambil menaip'],
    ['Papar & susun',
      'Senarai atau grid', 'Tukar paparan — pilihan disimpan',
      'Kumpulan masa berwarna', 'Hari ini / esok / minggu ini / kemudian',
      'Cari', 'Cari sebarang peringatan dengan pantas',
      'Templat', 'Sedia: ubat, perjalanan, kereta, bil…',
      'Cipta dengan suara', 'Sebut ayat, borang diisi'],
    ['Wawasan',
      'Papan hari ini', 'Tiba · kritikal · lewat · aktif + seterusnya',
      'Statistik', 'Jumlah · minggu ini · waktu puncak · paling kerap',
      'Log pemberitahuan', 'Setiap peringatan berbunyi direkod automatik'],
    ['Sistem & tetapan',
      'Kemas kini dalam apl', 'Semak dan pasang versi baharu — tanpa pelayar',
      'Sandaran', 'Simpan dan pulihkan peringatan',
      'Segerak awan', 'Segerak Google Drive tersulit',
      'Kunci apl', 'PIN atau cap jari',
      'Ke kalendar', 'Eksport .ics atau kongsi sebagai teks',
      'Pengaktifan', 'Kunci lesen universal — aktif atau nyahaktif'],
  ],
  'fil': [
    ['Mabilis na simula',
      'Pindutin ang +', 'Bubuksan ang dialog ng bagong paalala',
      'Pamagat', 'Ano ang aalalahanin — o idikta sa mik',
      'Pumili ng oras', 'Petsa at oras, Hijri o Gregorian',
      'I-save', 'Naka-iskedyul agad at lalabas sa Home',
      'Idagdag sa boses', 'Pindutin ang mik at sabihin: paalalahanan mo akong tawagan si Ahmed sa loob ng isang oras'],
    ['Uri ng paalala',
      'Pangkalahatan', 'Anumang pang-araw-araw na paalala',
      'Gamot', 'Dosis at bilang ng kurso',
      'Appointment', 'May lokasyon at imbitasyon',
      'Okasyon', 'Kaarawan at okasyon — taunan',
      'Mga bill', 'Paulit-ulit na bayad',
      'Biyahe', 'Mga biyahe at pag-alis',
      'Kotse', 'Serbisyo at renewal'],
    ['Oras at ulit',
      'Ulitin', 'Isahan · araw-araw · lingguhan · buwanan · taunan',
      'Taunang Hijri', 'Inuulit sa petsang Hijri kada taon',
      'Tuwing N araw', 'Sarili mong agwat',
      'Kurso ng gamot', 'Itakda ang kabuuang dosis; bumababa ang natitira',
      'Paunang abiso', '5 min / 15 min / oras / araw bago',
      'I-snooze', '5–60 minuto mula sa screen ng alarm'],
    ['Tunog at pagkaapurahan',
      'Aklatan ng tunog', 'Mga tono at tono ng device',
      'Itaas ang volume', 'Naririnig kahit silent/mahina — paunti-unti',
      'Lumalakas na kritikal', 'Lumalakas ang tunog at vibration kapag binalewala',
      'Hindi-mapapalampas', 'Sagutin ang maliit na suma bago isara',
      'Maaasahang alarm', 'Tumutunog kahit sarado o pagka-restart, full-screen'],
    ['I-customize at ilakip',
      'Sariling kulay', 'Isang kulay kada paalala, sa card',
      'Kahalagahan', 'Normal o kritikal na full-screen alarm',
      'Talang boses', 'Maglakip ng rekording',
      'Larawan / PDF', 'Maglakip ng imbitasyon o dokumento',
      'Lokasyon', 'Google Maps link o pumili ng lugar',
      'Live na preview', 'Tingnan ang paalala habang nagta-type'],
    ['Tingnan at ayusin',
      'Listahan o grid', 'Palitan ang view — naka-save ang pili',
      'Mga grupo ayon sa oras', 'Ngayon / bukas / ngayong linggo / mamaya',
      'Maghanap', 'Hanapin agad ang anumang paalala',
      'Mga template', 'Handa: gamot, biyahe, kotse, bill…',
      'Gumawa sa boses', 'Magsalita ng pangungusap, mapupunan ang form'],
    ['Mga insight',
      'Board ngayon', 'Nakatakda · kritikal · lampas · aktibo + susunod',
      'Estadistika', 'Kabuuan · ngayong linggo · peak na oras · pinakamadalas',
      'Log ng abiso', 'Bawat tumunog na paalala, awtomatikong naitatala'],
    ['Sistema at setting',
      'In-app update', 'Tingnan at i-install ang bagong bersyon — walang browser',
      'Backup', 'I-save at ibalik ang mga paalala',
      'Cloud sync', 'Naka-encrypt na Google Drive sync',
      'Lock ng app', 'PIN o fingerprint',
      'Idagdag sa kalendaryo', 'I-export ang .ics o ibahagi bilang teksto',
      'Activation', 'Universal license key — i-activate o i-deactivate'],
  ],
  'hi': [
    ['तेज़ शुरुआत',
      '+ दबाएँ', 'नया रिमाइंडर डायलॉग खोलता है',
      'शीर्षक', 'क्या याद रखना है — या माइक से बोलें',
      'समय चुनें', 'तारीख और समय, हिजरी या ग्रेगोरियन',
      'सहेजें', 'तुरंत शेड्यूल होकर होम पर दिखता है',
      'वॉइस से जोड़ें', 'माइक दबाएँ और कहें: एक घंटे में अहमद को कॉल करने की याद दिलाओ'],
    ['रिमाइंडर के प्रकार',
      'सामान्य', 'कोई भी रोज़ाना रिमाइंडर',
      'दवा', 'खुराक और कोर्स गिनती',
      'अपॉइंटमेंट', 'स्थान और निमंत्रण के साथ',
      'अवसर', 'जन्मदिन और अवसर — सालाना',
      'बिल', 'दोहराने वाले भुगतान',
      'यात्रा', 'यात्रा और प्रस्थान',
      'कार', 'सर्विस और नवीनीकरण'],
    ['समय और दोहराव',
      'दोहराएँ', 'एक बार · रोज़ · साप्ताहिक · मासिक · सालाना',
      'सालाना हिजरी', 'हर साल हिजरी तारीख पर दोहराता है',
      'हर N दिन', 'आपका अपना अंतराल',
      'दवा कोर्स', 'कुल खुराक तय करें; शेष घटता है',
      'पूर्व-सूचना', '5 मि / 15 मि / घंटा / दिन पहले',
      'स्नूज़', 'अलार्म स्क्रीन से 5–60 मिनट'],
    ['ध्वनि और तात्कालिकता',
      'ध्वनि लाइब्रेरी', 'अंतर्निहित टोन और डिवाइस टोन',
      'आवाज़ बढ़ाएँ', 'साइलेंट/कम पर भी सुनाई — वैकल्पिक क्रमिक',
      'बढ़ता क्रिटिकल', 'अनदेखा करने पर ध्वनि व कंपन बढ़ते हैं',
      'न चूकने वाला मोड', 'बंद करने से पहले छोटा जोड़ हल करें',
      'भरोसेमंद अलार्म', 'बंद या रीस्टार्ट पर भी बजे, फुल-स्क्रीन'],
    ['अनुकूलित करें व जोड़ें',
      'अपना रंग', 'हर रिमाइंडर का एक रंग, कार्ड पर दिखे',
      'महत्व', 'सामान्य या क्रिटिकल फुल-स्क्रीन अलार्म',
      'वॉइस नोट', 'एक रिकॉर्डिंग जोड़ें',
      'इमेज / PDF', 'निमंत्रण या दस्तावेज़ जोड़ें',
      'स्थान', 'Google Maps लिंक या जगह चुनें',
      'लाइव पूर्वावलोकन', 'टाइप करते समय रिमाइंडर देखें'],
    ['देखें और व्यवस्थित करें',
      'सूची या ग्रिड', 'दृश्य बदलें — आपका चयन सहेजा जाता है',
      'रंगीन समय-समूह', 'आज / कल / इस सप्ताह / बाद में',
      'खोज', 'कोई भी रिमाइंडर तेज़ी से खोजें',
      'टेम्पलेट', 'तैयार: दवा, यात्रा, कार, बिल…',
      'वॉइस से बनाएँ', 'एक वाक्य बोलें, फ़ॉर्म भर जाता है'],
    ['अंतर्दृष्टि',
      'आज का बोर्ड', 'देय · क्रिटिकल · विलंबित · सक्रिय + अगला',
      'आँकड़े', 'कुल · इस सप्ताह · व्यस्त घंटा · सबसे बार-बार',
      'सूचना लॉग', 'हर बजा रिमाइंडर अपने आप दर्ज'],
    ['सिस्टम और सेटिंग्स',
      'इन-ऐप अपडेट', 'नई वर्शन जांचें व इंस्टॉल करें — बिना ब्राउज़र',
      'बैकअप', 'अपने रिमाइंडर सहेजें व पुनर्स्थापित करें',
      'क्लाउड सिंक', 'एन्क्रिप्टेड Google Drive सिंक',
      'ऐप लॉक', 'PIN या फिंगरप्रिंट',
      'कैलेंडर में जोड़ें', '.ics निर्यात या टेक्स्ट साझा करें',
      'सक्रियण', 'यूनिवर्सल लाइसेंस कुंजी — सक्रिय या निष्क्रिय'],
  ],
  'bn': [
    ['দ্রুত শুরু',
      '+ চাপুন', 'নতুন রিমাইন্ডার ডায়ালগ খোলে',
      'শিরোনাম', 'কী মনে রাখবেন — বা মাইকে বলুন',
      'সময় বাছুন', 'তারিখ ও সময়, হিজরি বা গ্রেগরিয়ান',
      'সংরক্ষণ', 'সঙ্গে সঙ্গে শিডিউল হয়ে হোমে দেখায়',
      'ভয়েসে যোগ', 'মাইক চেপে বলুন: এক ঘণ্টা পরে আহমেদকে কল করার কথা মনে করিয়ে দাও'],
    ['রিমাইন্ডারের ধরন',
      'সাধারণ', 'যেকোনো দৈনন্দিন রিমাইন্ডার',
      'ওষুধ', 'ডোজ ও কোর্স গণনা',
      'অ্যাপয়েন্টমেন্ট', 'স্থান ও আমন্ত্রণসহ',
      'অনুষ্ঠান', 'জন্মদিন ও অনুষ্ঠান — বার্ষিক',
      'বিল', 'পুনরাবৃত্ত পরিশোধ',
      'ভ্রমণ', 'ভ্রমণ ও প্রস্থান',
      'গাড়ি', 'সার্ভিস ও নবায়ন'],
    ['সময় ও পুনরাবৃত্তি',
      'পুনরাবৃত্তি', 'একবার · দৈনিক · সাপ্তাহিক · মাসিক · বার্ষিক',
      'বার্ষিক হিজরি', 'প্রতি বছর হিজরি তারিখে পুনরাবৃত্ত',
      'প্রতি N দিন', 'আপনার নিজস্ব ব্যবধান',
      'ওষুধ কোর্স', 'মোট ডোজ ঠিক করুন; বাকি কমে',
      'আগাম সতর্কতা', '5 মি / 15 মি / ঘণ্টা / দিন আগে',
      'স্নুজ', 'অ্যালার্ম স্ক্রিন থেকে 5–60 মিনিট'],
    ['শব্দ ও জরুরিতা',
      'সাউন্ড লাইব্রেরি', 'অন্তর্নির্মিত টোন ও ডিভাইস টোন',
      'ভলিউম বাড়ান', 'সাইলেন্ট/নিচুতেও শোনা যায় — ধাপে ধাপে',
      'বাড়তে থাকা ক্রিটিক্যাল', 'উপেক্ষা করলে শব্দ ও কম্পন বাড়ে',
      'মিস-না মোড', 'বন্ধের আগে ছোট যোগফল মেলান',
      'নির্ভরযোগ্য অ্যালার্ম', 'বন্ধ বা রিস্টার্টেও বাজে, ফুল-স্ক্রিন'],
    ['কাস্টমাইজ ও সংযুক্ত',
      'নিজস্ব রং', 'প্রতি রিমাইন্ডারে এক রং, কার্ডে দেখায়',
      'গুরুত্ব', 'সাধারণ বা ক্রিটিক্যাল ফুল-স্ক্রিন অ্যালার্ম',
      'ভয়েস নোট', 'একটি রেকর্ডিং সংযুক্ত করুন',
      'ছবি / PDF', 'আমন্ত্রণ বা নথি সংযুক্ত করুন',
      'অবস্থান', 'Google Maps লিঙ্ক বা স্থান বাছুন',
      'লাইভ প্রিভিউ', 'টাইপ করার সময় রিমাইন্ডার দেখুন'],
    ['দেখা ও সাজানো',
      'তালিকা বা গ্রিড', 'ভিউ বদলান — আপনার পছন্দ সংরক্ষিত',
      'রঙিন সময়-গ্রুপ', 'আজ / আগামীকাল / এ সপ্তাহ / পরে',
      'অনুসন্ধান', 'যেকোনো রিমাইন্ডার দ্রুত খুঁজুন',
      'টেমপ্লেট', 'প্রস্তুত: ওষুধ, ভ্রমণ, গাড়ি, বিল…',
      'ভয়েসে তৈরি', 'একটি বাক্য বলুন, ফর্ম পূরণ হয়'],
    ['অন্তর্দৃষ্টি',
      'আজকের বোর্ড', 'বাকি · ক্রিটিক্যাল · বিলম্বিত · সক্রিয় + পরবর্তী',
      'পরিসংখ্যান', 'মোট · এ সপ্তাহ · ব্যস্ত সময় · সর্বাধিক',
      'বিজ্ঞপ্তি লগ', 'প্রতিটি বাজা রিমাইন্ডার স্বয়ংক্রিয় রেকর্ড'],
    ['সিস্টেম ও সেটিংস',
      'ইন-অ্যাপ আপডেট', 'নতুন সংস্করণ দেখুন ও ইনস্টল করুন — ব্রাউজার ছাড়া',
      'ব্যাকআপ', 'রিমাইন্ডার সংরক্ষণ ও পুনরুদ্ধার',
      'ক্লাউড সিঙ্ক', 'এনক্রিপ্টেড Google Drive সিঙ্ক',
      'অ্যাপ লক', 'PIN বা ফিঙ্গারপ্রিন্ট',
      'ক্যালেন্ডারে যোগ', '.ics রপ্তানি বা টেক্সট শেয়ার',
      'অ্যাক্টিভেশন', 'ইউনিভার্সাল লাইসেন্স কী — সক্রিয় বা নিষ্ক্রিয়'],
  ],
  'fa': [
    ['شروع سریع',
      'روی + بزن', 'پنجره یادآور جدید را باز می‌کند',
      'عنوان', 'چه چیزی یادآوری شود — یا با میکروفون بگو',
      'زمان را انتخاب کن', 'تاریخ و ساعت، هجری یا میلادی',
      'ذخیره', 'فوری زمان‌بندی و در خانه نمایش داده می‌شود',
      'افزودن صوتی', 'میکروفون را بزن و بگو: یک ساعت دیگر یادم بنداز به احمد زنگ بزنم'],
    ['انواع یادآور',
      'عمومی', 'هر یادآور روزمره',
      'دارو', 'دوزها و شمارش دوره',
      'قرار', 'با مکان و دعوت‌نامه',
      'مناسبت', 'تولدها و مناسبت‌ها — سالانه',
      'قبوض', 'پرداخت‌های تکراری',
      'سفر', 'سفرها و پروازها',
      'خودرو', 'سرویس و تمدیدها'],
    ['زمان و تکرار',
      'تکرار', 'یک‌بار · روزانه · هفتگی · ماهانه · سالانه',
      'سالانه هجری', 'هر سال در تاریخ هجری تکرار می‌شود',
      'هر N روز', 'بازه سفارشی خودت',
      'دوره دارو', 'تعداد کل دوز را تعیین کن؛ باقی کم می‌شود',
      'هشدار پیش‌هنگام', '۵د / ۱۵د / ساعت / روز قبل',
      'تعویق', '۵ تا ۶۰ دقیقه از صفحه زنگ'],
    ['صدا و فوریت',
      'کتابخانه صداها', 'آهنگ‌های داخلی به‌علاوه آهنگ‌های دستگاه',
      'بالا بردن صدا', 'در حالت بی‌صدا/کم هم شنیده می‌شود — تدریجی اختیاری',
      'بحرانی فزاینده', 'با بی‌توجهی صدا و لرزش بیشتر می‌شود',
      'حالت از‌دست‌نرفتنی', 'پیش از بستن یک جمع ساده را حل کن',
      'زنگ مطمئن', 'حتی بسته یا پس از ری‌استارت، تمام‌صفحه'],
    ['شخصی‌سازی و پیوست',
      'رنگ دلخواه', 'یک رنگ برای هر یادآور، روی کارت',
      'اهمیت', 'عادی یا بحرانی با زنگ تمام‌صفحه',
      'یادداشت صوتی', 'یک ضبط پیوست کن',
      'تصویر / PDF', 'دعوت‌نامه یا سند پیوست کن',
      'مکان', 'لینک گوگل‌مپ یا انتخاب نقطه',
      'پیش‌نمایش زنده', 'یادآور را هنگام نوشتن ببین'],
    ['نمایش و سازمان‌دهی',
      'فهرست یا شبکه', 'نما را عوض کن — انتخابت ذخیره می‌شود',
      'گروه‌های زمانی رنگی', 'امروز / فردا / این هفته / بعداً',
      'جستجو', 'هر یادآور را سریع پیدا کن',
      'قالب‌ها', 'آماده: دارو، سفر، خودرو، قبض…',
      'ساخت صوتی', 'یک جمله بگو، فرم پر می‌شود'],
    ['بینش‌ها',
      'تابلوی امروز', 'سررسید · بحرانی · معوق · فعال + بعدی',
      'آمار', 'کل · این هفته · ساعت اوج · پرتکرارترین',
      'گزارش اعلان‌ها', 'هر یادآور اجراشده خودکار ثبت می‌شود'],
    ['سیستم و تنظیمات',
      'به‌روزرسانی درون‌برنامه', 'نسخه‌های جدید را بررسی و نصب کن — بدون مرورگر',
      'پشتیبان', 'یادآورها را ذخیره و بازیابی کن',
      'همگام‌سازی ابری', 'همگام‌سازی رمزنگاری‌شده گوگل‌درایو',
      'قفل برنامه', 'پین یا اثر انگشت',
      'افزودن به تقویم', 'خروجی .ics یا اشتراک متنی',
      'فعال‌سازی', 'کلید مجوز عالمی — فعال یا غیرفعال'],
  ],
  'ru': [
    ['Быстрый старт',
      'Нажмите +', 'Откроет окно нового напоминания',
      'Заголовок', 'Что напомнить — или продиктуйте в микрофон',
      'Выберите время', 'Дата и время, хиджра или григориан',
      'Сохранить', 'Сразу планируется и видно на Главной',
      'Голосом', 'Нажмите микрофон и скажите: напомни позвонить Ахмеду через час'],
    ['Типы напоминаний',
      'Общее', 'Любое повседневное напоминание',
      'Лекарство', 'Дозы и счёт курса',
      'Встреча', 'С местом и приглашением',
      'Событие', 'Дни рождения и события — ежегодно',
      'Счета', 'Повторяющиеся платежи',
      'Поездка', 'Поездки и вылеты',
      'Машина', 'Обслуживание и продления'],
    ['Время и повтор',
      'Повтор', 'Раз · ежедневно · еженедельно · ежемесячно · ежегодно',
      'Ежегодно хиджра', 'Повтор по дате хиджры каждый год',
      'Каждые N дней', 'Свой интервал',
      'Курс лекарства', 'Задайте число доз; остаток убывает',
      'Предупредить заранее', '5 мин / 15 мин / час / день до',
      'Отложить', '5–60 минут с экрана будильника'],
    ['Звук и срочность',
      'Библиотека звуков', 'Встроенные сигналы плюс сигналы устройства',
      'Повышать громкость', 'Слышно в тихом/тихо — необязательно плавно',
      'Растущая критичность', 'Звук и вибрация растут при игнорировании',
      'Режим без промаха', 'Решите простой пример перед закрытием',
      'Надёжный будильник', 'Сработает закрытым или после перезагрузки, на весь экран'],
    ['Настройка и вложения',
      'Свой цвет', 'Цвет на напоминание, виден на карточке',
      'Важность', 'Обычное или критическое с полным экраном',
      'Голосовая заметка', 'Прикрепить запись',
      'Изображение / PDF', 'Прикрепить приглашение или документ',
      'Место', 'Ссылка Google Maps или выбор точки',
      'Живой просмотр', 'Видеть напоминание при наборе'],
    ['Вид и порядок',
      'Список или сетка', 'Сменить вид — выбор сохраняется',
      'Цветные группы по времени', 'Сегодня / завтра / на неделе / позже',
      'Поиск', 'Быстро найти любое напоминание',
      'Шаблоны', 'Готовые: лекарство, поездка, машина, счёт…',
      'Создать голосом', 'Скажите фразу — заполнит форму'],
    ['Аналитика',
      'Доска на сегодня', 'К сроку · критич. · просроч. · активн. + следующее',
      'Статистика', 'Всего · за неделю · пиковый час · самое частое',
      'Журнал уведомлений', 'Каждое сработавшее напоминание записывается'],
    ['Система и настройки',
      'Обновление в приложении', 'Проверить и установить новые версии — без браузера',
      'Резервная копия', 'Сохранить и восстановить напоминания',
      'Облачная синхронизация', 'Шифрованная синхронизация Google Drive',
      'Блокировка', 'PIN или отпечаток',
      'В календарь', 'Экспорт .ics или поделиться текстом',
      'Активация', 'Универсальный лицензионный ключ — включить или выключить'],
  ],
};

const Map<String, HgChrome> _hgChrome = {
  'en': HgChrome('Every feature — clearly explained', 'items', 'Updated: 2026-06-28'),
  'ar': HgChrome('كلّ ميزة — مشروحة بوضوح', 'عنصر', 'آخر تحديث: 2026-06-28'),
  'es': HgChrome('Cada función, explicada con claridad', 'elementos', 'Actualizado: 2026-06-28'),
  'de': HgChrome('Jede Funktion — klar erklärt', 'Einträge', 'Aktualisiert: 2026-06-28'),
  'fil': HgChrome('Bawat feature — malinaw na ipinaliwanag', 'item', 'Na-update: 2026-06-28'),
  'fr': HgChrome('Chaque fonction — clairement expliquée', 'éléments', 'Mis à jour : 2026-06-28'),
  'id': HgChrome('Setiap fitur — dijelaskan dengan jelas', 'item', 'Diperbarui: 2026-06-28'),
  'it': HgChrome('Ogni funzione — spiegata con chiarezza', 'elementi', 'Aggiornato: 2026-06-28'),
  'ms': HgChrome('Setiap ciri — diterang dengan jelas', 'item', 'Dikemas kini: 2026-06-28'),
  'hi': HgChrome('हर सुविधा — स्पष्ट रूप से समझाई गई', 'आइटम', 'अपडेट: 2026-06-28'),
  'bn': HgChrome('প্রতিটি ফিচার — স্পষ্টভাবে ব্যাখ্যা', 'আইটেম', 'আপডেট: 2026-06-28'),
  'fa': HgChrome('هر قابلیت — شفاف توضیح داده‌شده', 'مورد', 'به‌روزرسانی: 2026-06-28'),
  'ru': HgChrome('Каждая функция — понятно объяснена', 'элементов', 'Обновлено: 2026-06-28'),
};

List<HgSection> helpSections(String lang) => _build(_hg[lang] ?? _hg['en']!);
HgChrome helpChrome(String lang) => _hgChrome[lang] ?? _hgChrome['en']!;
