import 'package:flutter/material.dart';

// دليل استخدام تطبيق Alerts (تنبيهات) — مفهرس، ثلاثيّ الأبعاد، متعدّد اللغات،
// مع شرح تفصيليّ لكل عنصر (عنوان + وصف مختصر + شرح كامل بخطوات حيث يلزم).
//
// البنية مدفوعة بالبيانات: الأيقونات والألوان وحالة الطيّ مشتركة بين كل اللغات،
// ولكل لغة قائمة نصوص مسطّحة فقط (عنوان القسم ثم عنوان/وصف/شرح لكل عنصر).
class HgItem {
  final IconData icon;
  final String title;
  final String desc;
  final String detail; // شرح تفصيليّ يظهر عند فتح القسم.
  const HgItem(this.icon, this.title, this.desc, this.detail);
}

class HgSection {
  final IconData icon;
  final Color color;
  final bool expanded;
  final String title;
  final List<HgItem> items;
  const HgSection(this.icon, this.color, this.expanded, this.title, this.items);
}

class HgChrome {
  final String subtitle;
  final String items;
  final String updated;
  const HgChrome(this.subtitle, this.items, this.updated);
}

// ألوان الأقسام الثمانية.
const _c1 = Color(0xFF5C6BC0);
const _c2 = Color(0xFF26A69A);
const _c3 = Color(0xFFEF6C00);
const _c4 = Color(0xFF42A5F5);
const _c5 = Color(0xFF7E57C2);
const _c6 = Color(0xFFE53935);
const _c7 = Color(0xFFEC407A);
const _c8 = Color(0xFF6D4C41);

// أيقونة + لون + حالة الطيّ لكل قسم (مشتركة بين اللغات).
const List<IconData> _sectionIcons = [
  Icons.rocket_launch,
  Icons.category,
  Icons.event_repeat,
  Icons.volume_up,
  Icons.palette,
  Icons.dashboard_customize,
  Icons.insights,
  Icons.settings_suggest,
];
const List<Color> _sectionColors = [_c1, _c2, _c3, _c6, _c5, _c4, _c7, _c8];

// أيقونات عناصر كل قسم. أعداد العناصر: [5, 7, 6, 5, 6, 5, 3, 6].
const List<List<IconData>> _itemIcons = [
  [Icons.add_circle, Icons.title, Icons.schedule, Icons.check_circle, Icons.mic],
  [
    Icons.notifications_active,
    Icons.medication,
    Icons.event,
    Icons.celebration,
    Icons.receipt_long,
    Icons.flight,
    Icons.directions_car
  ],
  [
    Icons.repeat,
    Icons.mosque,
    Icons.event_repeat,
    Icons.medication_liquid,
    Icons.timer,
    Icons.snooze
  ],
  [
    Icons.library_music,
    Icons.volume_up,
    Icons.crisis_alert,
    Icons.calculate,
    Icons.alarm_on
  ],
  [
    Icons.color_lens,
    Icons.priority_high,
    Icons.mic_none,
    Icons.attach_file,
    Icons.place,
    Icons.visibility
  ],
  [
    Icons.view_agenda,
    Icons.palette_outlined,
    Icons.search,
    Icons.dashboard_customize,
    Icons.record_voice_over
  ],
  [Icons.today, Icons.bar_chart, Icons.history],
  [
    Icons.system_update,
    Icons.backup,
    Icons.cloud,
    Icons.lock,
    Icons.calendar_month,
    Icons.vpn_key
  ],
];

/// يبني أقسام الدليل من قائمة نصوص اللغة (عنوان القسم ثم عنوان/وصف/شرح لكل عنصر).
List<HgSection> _build(List<List<String>> langStrings) {
  final out = <HgSection>[];
  for (var s = 0; s < _sectionIcons.length; s++) {
    final strs = langStrings[s];
    final icons = _itemIcons[s];
    final items = <HgItem>[];
    for (var i = 0; i < icons.length; i++) {
      items.add(HgItem(
          icons[i], strs[1 + i * 3], strs[2 + i * 3], strs[3 + i * 3]));
    }
    out.add(
        HgSection(_sectionIcons[s], _sectionColors[s], s == 0, strs[0], items));
  }
  return out;
}

// نصوص الدليل لكل لغة. كل لغة = 8 أقسام، وكل قسم قائمة مسطّحة:
// [عنوان القسم، عنوان1، وصف1، شرح1، عنوان2، وصف2، شرح2، ...].
const Map<String, List<List<String>>> _hg = {
  'en': [
    ['Quick start',
      'Tap +', 'Opens the new-reminder sheet', 'The + button at the bottom opens the new-reminder sheet where you set everything in one place.',
      'Title', 'What to remember — or dictate it', 'Type the task, or tap the microphone inside the title field to dictate it instead of typing.',
      'Pick the time', 'Date and time, Hijri or Gregorian', 'Set the date and time; switch between Hijri and Gregorian with the calendar toggle in the picker.',
      'Save', 'Schedules instantly', 'Tap Save and the reminder is scheduled at once and appears on Home under its time group.',
      'Voice add', 'Speak a sentence on Home', 'Tap the small mic button on Home and say a full sentence; the time and task are filled in for you to confirm.'],
    ['Reminder types',
      'General', 'Any everyday reminder', 'The default type for any everyday task that does not fit a special category.',
      'Medication', 'Doses and a course count', 'Adds a dose field and an optional course count, so the app tracks how many doses remain.',
      'Appointment', 'With location and invitation', 'Lets you attach a map location (Google Maps link) and an invitation image or PDF.',
      'Occasion', 'Birthdays and events — yearly', 'Best for birthdays and yearly events; defaults to a yearly repeat so you never miss them.',
      'Bills', 'Recurring payments', 'For recurring payments; pair it with a monthly repeat to be reminded every billing cycle.',
      'Travel', 'Trips and departures', 'For trips and departures; add a pre-alert so you leave early enough.',
      'Car', 'Service and renewals', 'For service dates and document renewals; use a yearly or custom repeat for periodic maintenance.'],
    ['Time & repeat',
      'Repeat', 'Once · daily · weekly · monthly · yearly', 'Choose Once, Daily, Weekly (pick the weekdays), Monthly or Yearly from the repeat selector.',
      'Hijri yearly', 'Repeats on the Hijri date each year', 'Repeats on the same Hijri (lunar) date every year — ideal for Islamic occasions.',
      'Every N days', 'Your own custom interval', 'Choose a custom interval such as every 3 or 10 days when none of the standard repeats fit.',
      'Medication course', 'Remaining doses count down', 'Set the total number of doses; the remaining count goes down with each scheduled time.',
      'Pre-alert', '5 min / 15 min / hour / day before', 'Get an early heads-up 5 minutes, 15 minutes, an hour or a day before the actual time.',
      'Snooze', '5–60 minutes from the alarm', 'When the alarm rings, choose to postpone it 5 to 60 minutes from the alarm screen.'],
    ['Sound & urgency',
      'Sound library', 'Built-in tones plus device tones', 'Choose built-in tones, soft nature sounds, or any ringtone already on your device, including Huawei tones.',
      'Auto-raise volume', 'Heard on silent or low', 'Turn this on so the alarm raises the volume by itself and is heard even when the phone is silent or low.',
      'Escalating critical', 'Grows if ignored', 'For critical reminders the sound and vibration keep growing every few seconds until you respond.',
      'Cannot-miss mode', 'Solve a sum before dismissing', 'Enable it so you must solve a small addition problem before the alarm can be dismissed.',
      'Reliable alarm', 'Works closed, after reboot, full-screen', 'The alarm fires even when the app is closed or after a reboot, shows full-screen, and works offline.'],
    ['Customize & attach',
      'Custom color', 'Shown on the card', 'Pick a color for the reminder from the palette; it shows on the card so you can spot it at a glance.',
      'Importance', 'Normal or critical alarm', 'Set Normal for a quiet notification, or Critical to open the full-screen alarm with sound and vibration.',
      'Voice note', 'Attach a recording', 'Record a short voice memo and attach it to the reminder to play back later.',
      'Image / PDF', 'Invitation or document', 'Attach an invitation photo or a PDF document — handy for appointments and events.',
      'Location', 'Maps link or pick a spot', 'Paste a Google Maps share link or pick a spot, then open it for directions when the reminder fires.',
      'Live preview', 'See it as you type', 'See exactly how the reminder will look and read while you are still typing it.'],
    ['View & organize',
      'List or grid', 'Your choice is saved', 'Switch between a list and a card grid using the top toolbar button; your choice is remembered.',
      'Color time-groups', 'Today / tomorrow / this week / later', 'Reminders are grouped and color-coded by when they fire: today, tomorrow, this week and later.',
      'Search', 'Find any reminder fast', 'Tap the search icon and type any word to find a reminder instantly.',
      'Templates', 'Ready-made reminders', 'Open the templates sheet to start from a ready-made reminder (medication, travel, car, bill and more) with one tap.',
      'Voice creation', 'Speak; the form fills', 'Say a natural sentence like remind me to call Ahmed in an hour and the form fills itself for you to confirm.'],
    ['Insights',
      'Today board', 'Due, critical, overdue, active + next', 'A dashboard showing what is due today, what is critical, overdue and active, plus the next alarm.',
      'Statistics', 'Totals and patterns', 'See totals, this week count, your busiest hour and your most frequent reminder.',
      'Notification log', 'Logged automatically', 'Every reminder that fires is recorded automatically in the log so you can review what already went off.'],
    ['System & settings',
      'In-app update', 'No browser needed', 'Open Settings → About & help → Check for updates; the app downloads and installs the new version itself.',
      'Backup', 'Save and restore', 'From Settings → Security & backup, save an encrypted backup of your reminders and restore it later on any device.',
      'Cloud sync', 'Encrypted Google Drive', 'In the Backup screen choose Google Drive, sign in, set the same encryption passphrase on every device, and turn on auto-sync; the data is encrypted before it leaves the phone.',
      'App lock', 'PIN or fingerprint', 'Protect the app with a PIN or your fingerprint from Settings → Security & backup.',
      'Add to calendar', 'Export .ics or share', 'Export any reminder as a .ics file to add it to your phone calendar, or share it as plain text.',
      'Activation', 'Universal license key', 'Enter the universal license key once to activate; you can deactivate later to test activation on another device.'],
  ],
  'ar': [
    ['البداية السريعة',
      'اضغط +', 'يفتح حوار التنبيه الجديد', 'زرّ + في الأسفل يفتح ورقة التنبيه الجديد حيث تضبط كلّ شيء في مكان واحد.',
      'العنوان', 'ما تريد تذكّره أو أمْلِه', 'اكتب المهمّة، أو اضغط الميكروفون داخل حقل العنوان لإملائها بدل الكتابة.',
      'اختر الوقت', 'تاريخ ووقت، هجريّ أو ميلاديّ', 'اضبط التاريخ والوقت؛ بدّل بين الهجريّ والميلاديّ من زرّ التقويم في المنتقي.',
      'حفظ', 'يُجدوَل فورًا', 'اضغط حفظ فيُجدوَل التنبيه فورًا ويظهر في الرئيسية ضمن مجموعته الزمنية.',
      'إضافة صوتية', 'انطق جملة في الرئيسية', 'اضغط زرّ الميكروفون في الرئيسية وانطق جملة كاملة؛ يُستنتج الوقت والمهمّة لتراجعهما.'],
    ['أنواع التنبيه',
      'عام', 'أيّ تذكير يوميّ', 'النوع الافتراضيّ لأيّ مهمّة يوميّة لا تندرج تحت فئة خاصّة.',
      'دواء', 'جرعات وعدد كورس', 'يضيف حقل جرعة وعدد كورس اختياريًّا، فيتتبّع التطبيق كم جرعة تبقّت.',
      'موعد', 'مع موقع ودعوة', 'يتيح إرفاق موقع على الخرائط (رابط جوجل) ودعوة صورة أو PDF.',
      'مناسبة', 'أعياد ومناسبات — سنويّ', 'الأنسب للأعياد والمناسبات السنوية؛ يفترض تكرارًا سنويًّا كي لا تفوتك.',
      'فواتير', 'مدفوعات متكرّرة', 'للمدفوعات المتكرّرة؛ اقرنها بتكرار شهريّ لتُذكَّر كلّ دورة فوترة.',
      'سفر', 'رحلات وإقلاع', 'للرحلات ومواعيد الإقلاع؛ أضِف تنبيهًا مسبقًا لتخرج مبكّرًا بما يكفي.',
      'سيارة', 'صيانة وتجديدات', 'لمواعيد الصيانة وتجديد الوثائق؛ استخدم تكرارًا سنويًّا أو مخصّصًا للصيانة الدورية.'],
    ['الوقت والتكرار',
      'التكرار', 'مرّة · يوميّ · أسبوعيّ · شهريّ · سنويّ', 'اختر مرّة أو يوميّ أو أسبوعيّ (حدّد الأيام) أو شهريّ أو سنويّ من منتقي التكرار.',
      'سنويّ هجريّ', 'يتكرّر في التاريخ الهجريّ كلّ عام', 'يتكرّر في التاريخ الهجريّ نفسه كلّ عام — مثاليّ للمناسبات الإسلامية.',
      'كلّ N يوم', 'فاصل مخصّص باختيارك', 'اختر فاصلًا مخصّصًا كأن يكون كلّ 3 أو 10 أيام حين لا يناسبك أيّ تكرار قياسيّ.',
      'كورس دواء', 'المتبقّي ينقص', 'حدّد عدد الجرعات الكلّي؛ ينقص العدد المتبقّي مع كلّ موعد مجدوَل.',
      'تنبيه مسبق', '5د / 15د / ساعة / يوم قبل', 'تنبيه مبكّر قبل الموعد الفعليّ بـ5 دقائق أو 15 دقيقة أو ساعة أو يوم.',
      'غفوة', '5–60 دقيقة من شاشة المنبّه', 'عند رنين المنبّه يمكنك تأجيله من 5 إلى 60 دقيقة من شاشة المنبّه.'],
    ['الصوت والإلحاح',
      'مكتبة الأصوات', 'نغمات مدمجة + نغمات جهازك', 'اختر نغمات مدمجة أو أصواتًا طبيعية ناعمة أو أيّ نغمة على جهازك بما فيها نغمات هواوي.',
      'رفع الصوت تلقائيًّا', 'يُسمَع مع الصامت/المنخفض', 'فعّله ليرفع المنبّه الصوت تلقائيًّا فيُسمَع حتى لو كان الهاتف صامتًا أو منخفضًا.',
      'تصعيد حرج', 'يزداد إن تُجوهِل', 'للتنبيهات الحرجة يتصاعد الصوت والاهتزاز كلّ بضع ثوانٍ حتى تتفاعل.',
      'وضع لا يُفوَّت', 'احسب مسألة قبل الإيقاف', 'فعّله فيلزمك حلّ مسألة جمع بسيطة قبل أن يُمكن إيقاف المنبّه.',
      'منبّه موثوق', 'يعمل مغلقًا وبعد التشغيل وشاشة كاملة', 'يعمل المنبّه حتى والتطبيق مغلق أو بعد إعادة التشغيل، بشاشة كاملة، ودون إنترنت.'],
    ['التخصيص والمرفقات',
      'لون مخصّص', 'يظهر على البطاقة', 'اختر لونًا للتنبيه من اللوحة؛ يظهر على البطاقة لتميّزه بنظرة سريعة.',
      'الأهمّية', 'عاديّ أو منبّه حرج', 'اختر عاديًّا لإشعار هادئ، أو حرجًا لفتح شاشة المنبّه الكاملة بالصوت والاهتزاز.',
      'ملاحظة صوتية', 'أرفِق تسجيلًا', 'سجّل مذكّرة صوتية قصيرة وأرفقها بالتنبيه لتشغيلها لاحقًا.',
      'صورة / PDF', 'دعوة أو مستند', 'أرفِق صورة دعوة أو مستند PDF — مفيد للمواعيد والمناسبات.',
      'الموقع', 'رابط خرائط أو اختيار نقطة', 'الصق رابط مشاركة خرائط جوجل أو اختر نقطة، ثم افتحه للاتجاهات عند رنين التنبيه.',
      'معاينة حيّة', 'شاهده وأنت تكتب', 'شاهد كيف سيبدو التنبيه ويُقرأ وأنت لا تزال تكتبه.'],
    ['العرض والتنظيم',
      'قائمة أو مربّعات', 'يُحفظ اختيارك', 'بدّل بين القائمة وشبكة البطاقات من زرّ الشريط العلويّ؛ يُحفظ اختيارك.',
      'تجميع زمنيّ ملوّن', 'اليوم / غدًا / هذا الأسبوع / لاحقًا', 'تُجمَّع التنبيهات وتُلوَّن حسب وقت إطلاقها: اليوم، غدًا، هذا الأسبوع، ولاحقًا.',
      'بحث', 'اعثر على أيّ تنبيه بسرعة', 'اضغط أيقونة البحث واكتب أيّ كلمة لتجد تنبيهًا فورًا.',
      'قوالب جاهزة', 'تنبيهات معدّة مسبقًا', 'افتح ورقة القوالب لتبدأ من تنبيه جاهز (أدوية، سفر، سيارة، فاتورة وغيرها) بنقرة.',
      'إنشاء صوتيّ', 'انطق فيُملأ النموذج', 'انطق جملة طبيعية مثل ذكّرني أتصل بأحمد بعد ساعة فيملأ النموذج نفسه لتراجعه.'],
    ['المتابعة والإحصاء',
      'لوحة اليوم', 'قادمة · حرِجة · فائتة · نشطة + التالي', 'لوحة تعرض ما يحلّ اليوم وما هو حرج وفائت ونشط، إضافةً للمنبّه التالي.',
      'إحصاءات', 'إجماليات وأنماط', 'اطّلع على الإجمالي وعدّ هذا الأسبوع وأكثر ساعاتك ازدحامًا وأكثر تنبيهاتك تكرارًا.',
      'سجلّ التنبيهات', 'يُسجَّل تلقائيًّا', 'كلّ تنبيه يُطلَق يُسجَّل تلقائيًّا في السجل لتراجع ما انطلق سابقًا.'],
    ['النظام والإعدادات',
      'تحديث داخليّ', 'بلا متصفّح', 'افتح الإعدادات ← حول ومساعدة ← تحقّق من التحديث؛ ينزّل التطبيق النسخة الجديدة ويثبّتها بنفسه.',
      'نسخ احتياطيّ', 'احفظ واسترجع', 'من الإعدادات ← الأمان والنسخ، احفظ نسخة مشفّرة من تنبيهاتك واسترجعها لاحقًا على أيّ جهاز.',
      'مزامنة سحابية', 'Google Drive مشفّرة', 'في شاشة النسخ اختر Google Drive وسجّل الدخول واضبط عبارة التشفير نفسها على كلّ جهاز وفعّل المزامنة التلقائية؛ تُشفَّر البيانات قبل مغادرتها الهاتف.',
      'قفل التطبيق', 'رقم سرّي أو بصمة', 'احمِ التطبيق برقم سرّي أو ببصمتك من الإعدادات ← الأمان والنسخ.',
      'إضافة للتقويم', 'صدّر .ics أو شارك', 'صدّر أيّ تنبيه كملفّ .ics لإضافته إلى تقويم هاتفك، أو شاركه كنصّ عاديّ.',
      'التفعيل', 'مفتاح ترخيص عالميّ', 'أدخل مفتاح الترخيص العالميّ مرّة للتفعيل؛ ويمكنك إلغاء التفعيل لاحقًا لاختباره على جهاز آخر.'],
  ],
  'es': [
    ['Inicio rápido',
      'Toca +', 'Abre el panel de nuevo recordatorio', 'El botón + de abajo abre el panel del nuevo recordatorio donde ajustas todo en un solo lugar.',
      'Título', 'Qué recordar — o díctalo', 'Escribe la tarea o toca el micrófono dentro del campo de título para dictarla en vez de escribir.',
      'Elige la hora', 'Fecha y hora, hijri o gregoriano', 'Ajusta la fecha y la hora; cambia entre hijri y gregoriano con el botón de calendario del selector.',
      'Guardar', 'Se programa al instante', 'Toca Guardar y el recordatorio se programa al momento y aparece en Inicio en su grupo de tiempo.',
      'Añadir por voz', 'Di una frase en Inicio', 'Toca el botón de micrófono en Inicio y di una frase completa; la hora y la tarea se rellenan para confirmar.'],
    ['Tipos de recordatorio',
      'General', 'Cualquier recordatorio diario', 'El tipo por defecto para cualquier tarea diaria que no encaje en una categoría especial.',
      'Medicación', 'Dosis y recuento del tratamiento', 'Añade un campo de dosis y un recuento opcional, para que la app controle cuántas dosis quedan.',
      'Cita', 'Con ubicación e invitación', 'Permite adjuntar una ubicación del mapa (enlace de Google Maps) y una invitación en imagen o PDF.',
      'Evento', 'Cumpleaños y eventos — anual', 'Ideal para cumpleaños y eventos anuales; usa repetición anual para no olvidarlos.',
      'Facturas', 'Pagos recurrentes', 'Para pagos recurrentes; combínalo con una repetición mensual para recordar cada ciclo.',
      'Viaje', 'Viajes y salidas', 'Para viajes y salidas; añade un aviso previo para salir con tiempo.',
      'Coche', 'Mantenimiento y renovaciones', 'Para fechas de mantenimiento y renovación de documentos; usa una repetición anual o personalizada.'],
    ['Hora y repetición',
      'Repetir', 'Una vez · diario · semanal · mensual · anual', 'Elige Una vez, Diario, Semanal (elige los días), Mensual o Anual en el selector de repetición.',
      'Anual hijri', 'En la fecha hijri cada año', 'Se repite en la misma fecha hijri (lunar) cada año, ideal para ocasiones islámicas.',
      'Cada N días', 'Tu intervalo personalizado', 'Elige un intervalo propio como cada 3 o 10 días cuando ninguna repetición estándar encaja.',
      'Tratamiento', 'Lo restante baja', 'Fija el total de dosis; el recuento restante baja con cada hora programada.',
      'Aviso previo', '5 min / 15 min / hora / día antes', 'Recibe un aviso anticipado 5 min, 15 min, una hora o un día antes de la hora real.',
      'Posponer', '5–60 minutos desde la alarma', 'Cuando suena la alarma, puedes posponerla de 5 a 60 minutos desde la pantalla de alarma.'],
    ['Sonido y urgencia',
      'Biblioteca de sonidos', 'Tonos integrados y del dispositivo', 'Elige tonos integrados, sonidos suaves de la naturaleza o cualquier tono de tu dispositivo, incluidos los de Huawei.',
      'Subir volumen', 'Se oye en silencio o bajo', 'Actívalo para que la alarma suba el volumen sola y se oiga aunque el teléfono esté en silencio o bajo.',
      'Crítico creciente', 'Crece si se ignora', 'En los recordatorios críticos el sonido y la vibración crecen cada pocos segundos hasta que respondes.',
      'Modo imperdible', 'Resuelve una suma para descartar', 'Actívalo para tener que resolver una pequeña suma antes de poder descartar la alarma.',
      'Alarma fiable', 'Cerrada, tras reinicio, pantalla completa', 'La alarma suena aunque la app esté cerrada o tras reiniciar, en pantalla completa y sin conexión.'],
    ['Personalizar y adjuntar',
      'Color propio', 'Visible en la tarjeta', 'Elige un color para el recordatorio en la paleta; aparece en la tarjeta para reconocerlo de un vistazo.',
      'Importancia', 'Normal o alarma crítica', 'Pon Normal para un aviso discreto, o Crítico para abrir la alarma a pantalla completa con sonido y vibración.',
      'Nota de voz', 'Adjunta una grabación', 'Graba una nota de voz corta y adjúntala al recordatorio para reproducirla luego.',
      'Imagen / PDF', 'Invitación o documento', 'Adjunta una foto de invitación o un documento PDF, útil para citas y eventos.',
      'Ubicación', 'Enlace de mapa o un punto', 'Pega un enlace de Google Maps o elige un punto, y ábrelo para llegar cuando suene el recordatorio.',
      'Vista previa', 'Velo mientras escribes', 'Ve exactamente cómo se verá y leerá el recordatorio mientras lo escribes.'],
    ['Ver y organizar',
      'Lista o cuadrícula', 'Se guarda tu elección', 'Cambia entre lista y cuadrícula de tarjetas con el botón de la barra superior; se recuerda tu elección.',
      'Grupos por tiempo', 'Hoy / mañana / esta semana / después', 'Los recordatorios se agrupan y colorean según cuándo suenan: hoy, mañana, esta semana y después.',
      'Buscar', 'Encuentra cualquiera rápido', 'Toca el icono de buscar y escribe una palabra para encontrar un recordatorio al instante.',
      'Plantillas', 'Recordatorios listos', 'Abre el panel de plantillas para empezar desde un recordatorio listo (medicación, viaje, coche, factura y más) con un toque.',
      'Crear por voz', 'Habla; el formulario se rellena', 'Di una frase natural y el formulario se rellena solo para que lo confirmes.'],
    ['Análisis',
      'Panel de hoy', 'Pendiente, crítico, vencido, activo + próximo', 'Un panel que muestra lo pendiente hoy, lo crítico, lo vencido y lo activo, más la próxima alarma.',
      'Estadísticas', 'Totales y patrones', 'Consulta totales, el recuento de esta semana, tu hora más activa y tu recordatorio más frecuente.',
      'Registro de avisos', 'Se registra solo', 'Cada recordatorio que suena se registra automáticamente para que revises lo que ya saltó.'],
    ['Sistema y ajustes',
      'Actualización integrada', 'Sin navegador', 'Abre Ajustes → Acerca y ayuda → Buscar actualizaciones; la app descarga e instala la nueva versión sola.',
      'Copia de seguridad', 'Guarda y restaura', 'En Ajustes → Seguridad y copia, guarda una copia cifrada de tus recordatorios y restáurala luego en cualquier dispositivo.',
      'Sync en la nube', 'Google Drive cifrado', 'En la pantalla de copia elige Google Drive, inicia sesión, pon la misma frase de cifrado en cada dispositivo y activa la sync automática; los datos se cifran antes de salir del teléfono.',
      'Bloqueo de app', 'PIN o huella', 'Protege la app con un PIN o tu huella desde Ajustes → Seguridad y copia.',
      'Añadir al calendario', 'Exporta .ics o comparte', 'Exporta un recordatorio como archivo .ics para añadirlo al calendario del teléfono, o compártelo como texto.',
      'Activación', 'Clave de licencia universal', 'Introduce la clave de licencia universal una vez para activar; puedes desactivar luego para probarla en otro dispositivo.'],
  ],
  'de': [
    ['Schnellstart',
      'Auf + tippen', 'Öffnet das Fenster für neue Erinnerung', 'Die +-Schaltfläche unten öffnet das Fenster, in dem du alles an einem Ort einstellst.',
      'Titel', 'Woran erinnern — oder diktieren', 'Tippe die Aufgabe ein oder tippe das Mikrofon im Titelfeld, um sie zu diktieren.',
      'Zeit wählen', 'Datum und Uhrzeit, Hidschri oder gregorianisch', 'Lege Datum und Uhrzeit fest; wechsle im Auswähler mit dem Kalenderschalter zwischen Hidschri und gregorianisch.',
      'Speichern', 'Wird sofort geplant', 'Tippe Speichern und die Erinnerung wird sofort geplant und auf Start in ihrer Zeitgruppe angezeigt.',
      'Per Sprache', 'Auf Start einen Satz sprechen', 'Tippe das kleine Mikrofon auf Start und sprich einen ganzen Satz; Zeit und Aufgabe werden zur Bestätigung ausgefüllt.'],
    ['Erinnerungstypen',
      'Allgemein', 'Jede alltägliche Erinnerung', 'Der Standardtyp für jede Alltagsaufgabe, die in keine besondere Kategorie passt.',
      'Medikament', 'Dosen und Kur-Zählung', 'Fügt ein Dosisfeld und eine optionale Kur-Zählung hinzu, damit die App die verbleibenden Dosen verfolgt.',
      'Termin', 'Mit Ort und Einladung', 'Erlaubt das Anhängen eines Kartenorts (Google-Maps-Link) und einer Einladung als Bild oder PDF.',
      'Anlass', 'Geburtstage und Anlässe — jährlich', 'Ideal für Geburtstage und jährliche Anlässe; nutzt standardmäßig eine jährliche Wiederholung.',
      'Rechnungen', 'Wiederkehrende Zahlungen', 'Für wiederkehrende Zahlungen; kombiniere es mit einer monatlichen Wiederholung für jeden Zyklus.',
      'Reise', 'Reisen und Abflüge', 'Für Reisen und Abflüge; füge einen Vorab-Hinweis hinzu, um früh genug loszukommen.',
      'Auto', 'Wartung und Verlängerungen', 'Für Wartungstermine und Dokumentverlängerungen; nutze eine jährliche oder eigene Wiederholung.'],
    ['Zeit & Wiederholung',
      'Wiederholen', 'Einmal · täglich · wöchentlich · monatlich · jährlich', 'Wähle Einmal, Täglich, Wöchentlich (Wochentage wählen), Monatlich oder Jährlich im Auswähler.',
      'Jährlich Hidschri', 'Jährlich am Hidschri-Datum', 'Wiederholt sich jedes Jahr am selben Hidschri-Datum, ideal für islamische Anlässe.',
      'Alle N Tage', 'Dein eigenes Intervall', 'Wähle ein eigenes Intervall wie alle 3 oder 10 Tage, wenn keine Standardwiederholung passt.',
      'Medikamenten-Kur', 'Rest zählt herunter', 'Lege die Gesamtzahl der Dosen fest; der Rest zählt mit jedem geplanten Zeitpunkt herunter.',
      'Vorab-Hinweis', '5 Min / 15 Min / Stunde / Tag vorher', 'Erhalte einen frühen Hinweis 5 Min, 15 Min, eine Stunde oder einen Tag vor der eigentlichen Zeit.',
      'Schlummern', '5–60 Minuten vom Wecker', 'Wenn der Wecker klingelt, kannst du ihn vom Wecker-Bildschirm 5 bis 60 Minuten verschieben.'],
    ['Ton & Dringlichkeit',
      'Klangbibliothek', 'Integrierte und Gerätetöne', 'Wähle integrierte Töne, sanfte Naturklänge oder jeden Ton auf deinem Gerät, auch Huawei-Töne.',
      'Lautstärke anheben', 'Hörbar bei lautlos/leise', 'Aktiviere es, damit der Wecker die Lautstärke selbst anhebt und auch bei lautlos oder leise hörbar ist.',
      'Steigende Dringlichkeit', 'Wächst bei Ignorieren', 'Bei kritischen Erinnerungen wachsen Ton und Vibration alle paar Sekunden, bis du reagierst.',
      'Unverpassbar-Modus', 'Summe lösen vor dem Beenden', 'Aktiviere es, damit du eine kleine Additionsaufgabe lösen musst, bevor der Wecker beendet werden kann.',
      'Zuverlässiger Wecker', 'Geschlossen, nach Neustart, Vollbild', 'Der Wecker klingelt auch geschlossen oder nach Neustart, im Vollbild und offline.'],
    ['Anpassen & anhängen',
      'Eigene Farbe', 'Auf der Karte sichtbar', 'Wähle eine Farbe aus der Palette; sie erscheint auf der Karte, damit du sie schnell erkennst.',
      'Wichtigkeit', 'Normal oder kritischer Wecker', 'Wähle Normal für einen leisen Hinweis oder Kritisch für den Vollbild-Wecker mit Ton und Vibration.',
      'Sprachnotiz', 'Eine Aufnahme anhängen', 'Nimm eine kurze Sprachnotiz auf und hänge sie an, um sie später abzuspielen.',
      'Bild / PDF', 'Einladung oder Dokument', 'Hänge ein Einladungsfoto oder ein PDF-Dokument an, praktisch für Termine und Anlässe.',
      'Ort', 'Karten-Link oder Punkt wählen', 'Füge einen Google-Maps-Link ein oder wähle einen Punkt und öffne ihn für die Route, wenn die Erinnerung klingelt.',
      'Live-Vorschau', 'Beim Tippen sehen', 'Sieh genau, wie die Erinnerung aussieht und liest, während du sie noch tippst.'],
    ['Ansicht & Organisation',
      'Liste oder Raster', 'Auswahl wird gespeichert', 'Wechsle mit der oberen Schaltfläche zwischen Liste und Kartenraster; deine Auswahl wird gemerkt.',
      'Farbige Zeitgruppen', 'Heute / morgen / diese Woche / später', 'Erinnerungen werden nach Auslösezeit gruppiert und farbig markiert: heute, morgen, diese Woche und später.',
      'Suche', 'Jede Erinnerung schnell finden', 'Tippe das Suchsymbol und gib ein Wort ein, um eine Erinnerung sofort zu finden.',
      'Vorlagen', 'Fertige Erinnerungen', 'Öffne die Vorlagen, um mit einem Tippen aus einer fertigen Erinnerung zu starten (Medikament, Reise, Auto, Rechnung u. a.).',
      'Per Sprache erstellen', 'Sprich; das Formular füllt sich', 'Sprich einen natürlichen Satz und das Formular füllt sich selbst zur Bestätigung.'],
    ['Einblicke',
      'Heute-Übersicht', 'Fällig, kritisch, überfällig, aktiv + nächster', 'Eine Übersicht zeigt, was heute fällig, kritisch, überfällig und aktiv ist, plus den nächsten Wecker.',
      'Statistik', 'Summen und Muster', 'Sieh Summen, die Anzahl dieser Woche, deine geschäftigste Stunde und deine häufigste Erinnerung.',
      'Mitteilungsprotokoll', 'Automatisch erfasst', 'Jede ausgelöste Erinnerung wird automatisch protokolliert, sodass du Vergangenes prüfen kannst.'],
    ['System & Einstellungen',
      'In-App-Update', 'Kein Browser nötig', 'Öffne Einstellungen → Info & Hilfe → Nach Updates suchen; die App lädt und installiert die neue Version selbst.',
      'Sicherung', 'Speichern und wiederherstellen', 'Unter Einstellungen → Sicherheit & Sicherung speicherst du eine verschlüsselte Sicherung und stellst sie später auf jedem Gerät wieder her.',
      'Cloud-Sync', 'Verschlüsseltes Google Drive', 'Wähle im Sicherungsbildschirm Google Drive, melde dich an, setze auf jedem Gerät dieselbe Passphrase und aktiviere Auto-Sync; die Daten werden vor dem Hochladen verschlüsselt.',
      'App-Sperre', 'PIN oder Fingerabdruck', 'Schütze die App mit einer PIN oder deinem Fingerabdruck unter Einstellungen → Sicherheit & Sicherung.',
      'Zum Kalender', '.ics exportieren oder teilen', 'Exportiere eine Erinnerung als .ics-Datei für deinen Telefonkalender oder teile sie als Text.',
      'Aktivierung', 'Universeller Lizenzschlüssel', 'Gib den universellen Lizenzschlüssel einmal ein; du kannst ihn später deaktivieren, um ihn auf einem anderen Gerät zu testen.'],
  ],
  'fr': [
    ['Démarrage rapide',
      'Touchez +', 'Ouvre la feuille du nouveau rappel', 'Le bouton + en bas ouvre la feuille du nouveau rappel où vous réglez tout au même endroit.',
      'Titre', 'Quoi retenir — ou dictez-le', 'Saisissez la tâche ou touchez le micro dans le champ du titre pour la dicter.',
      'Choisir l’heure', 'Date et heure, hégirien ou grégorien', 'Réglez la date et l’heure ; basculez entre hégirien et grégorien avec le bouton calendrier du sélecteur.',
      'Enregistrer', 'Programmé aussitôt', 'Touchez Enregistrer et le rappel est programmé aussitôt et affiché à l’Accueil dans son groupe horaire.',
      'Ajout vocal', 'Dites une phrase à l’Accueil', 'Touchez le petit micro à l’Accueil et dites une phrase complète ; l’heure et la tâche sont remplies à confirmer.'],
    ['Types de rappel',
      'Général', 'Tout rappel du quotidien', 'Le type par défaut pour toute tâche quotidienne qui n’entre pas dans une catégorie spéciale.',
      'Médicament', 'Doses et décompte de la cure', 'Ajoute un champ de dose et un décompte optionnel, pour suivre les doses restantes.',
      'Rendez-vous', 'Avec lieu et invitation', 'Permet de joindre un lieu sur la carte (lien Google Maps) et une invitation image ou PDF.',
      'Occasion', 'Anniversaires et événements — annuel', 'Idéal pour les anniversaires et événements annuels ; répétition annuelle par défaut.',
      'Factures', 'Paiements récurrents', 'Pour les paiements récurrents ; associez une répétition mensuelle pour chaque cycle.',
      'Voyage', 'Voyages et départs', 'Pour les voyages et départs ; ajoutez une pré-alerte pour partir à temps.',
      'Voiture', 'Entretien et renouvellements', 'Pour les dates d’entretien et de renouvellement de documents ; répétition annuelle ou personnalisée.'],
    ['Heure et répétition',
      'Répéter', 'Une fois · quotidien · hebdo · mensuel · annuel', 'Choisissez Une fois, Quotidien, Hebdo (choisir les jours), Mensuel ou Annuel dans le sélecteur.',
      'Annuel hégirien', 'À la date hégirienne chaque année', 'Se répète à la même date hégirienne chaque année, idéal pour les occasions islamiques.',
      'Tous les N jours', 'Votre intervalle personnalisé', 'Choisissez un intervalle propre comme tous les 3 ou 10 jours si aucune répétition standard ne convient.',
      'Cure de médicament', 'Le reste décompte', 'Définissez le total des doses ; le reste décompte à chaque heure programmée.',
      'Pré-alerte', '5 min / 15 min / heure / jour avant', 'Recevez une alerte anticipée 5 min, 15 min, une heure ou un jour avant l’heure réelle.',
      'Répéter l’alarme', '5–60 minutes depuis l’alarme', 'Quand l’alarme sonne, repoussez-la de 5 à 60 minutes depuis l’écran d’alarme.'],
    ['Son et urgence',
      'Bibliothèque de sons', 'Sonneries intégrées et de l’appareil', 'Choisissez des sonneries intégrées, des sons doux de la nature, ou tout son de votre appareil, y compris Huawei.',
      'Monter le volume', 'Audible en silencieux ou bas', 'Activez pour que l’alarme monte le volume elle-même et soit audible même en silencieux ou bas.',
      'Critique croissant', 'Monte si ignoré', 'Pour les rappels critiques, le son et la vibration montent toutes les quelques secondes jusqu’à votre réponse.',
      'Mode incontournable', 'Résoudre une somme pour fermer', 'Activez pour devoir résoudre une petite addition avant de pouvoir fermer l’alarme.',
      'Alarme fiable', 'Fermée, après redémarrage, plein écran', 'L’alarme sonne même app fermée ou après redémarrage, en plein écran et hors ligne.'],
    ['Personnaliser et joindre',
      'Couleur propre', 'Visible sur la carte', 'Choisissez une couleur dans la palette ; elle apparaît sur la carte pour la repérer d’un coup d’œil.',
      'Importance', 'Normal ou alarme critique', 'Mettez Normal pour un avis discret, ou Critique pour ouvrir l’alarme plein écran avec son et vibration.',
      'Note vocale', 'Joindre un enregistrement', 'Enregistrez une courte note vocale et joignez-la au rappel pour l’écouter plus tard.',
      'Image / PDF', 'Invitation ou document', 'Joignez une photo d’invitation ou un document PDF, pratique pour rendez-vous et événements.',
      'Lieu', 'Lien carte ou choisir un point', 'Collez un lien Google Maps ou choisissez un point, puis ouvrez-le pour l’itinéraire quand le rappel sonne.',
      'Aperçu en direct', 'Voyez-le en tapant', 'Voyez exactement comment le rappel s’affiche et se lit pendant que vous le tapez.'],
    ['Affichage et organisation',
      'Liste ou grille', 'Votre choix est gardé', 'Basculez entre liste et grille de cartes avec le bouton de la barre du haut ; votre choix est mémorisé.',
      'Groupes par temps', 'Aujourd’hui / demain / cette semaine / plus tard', 'Les rappels sont groupés et colorés selon leur heure : aujourd’hui, demain, cette semaine et plus tard.',
      'Recherche', 'Trouver vite un rappel', 'Touchez la loupe et tapez un mot pour trouver un rappel instantanément.',
      'Modèles', 'Rappels prêts', 'Ouvrez les modèles pour partir d’un rappel prêt (médicament, voyage, voiture, facture, etc.) d’un toucher.',
      'Création vocale', 'Parlez ; le formulaire se remplit', 'Dites une phrase naturelle et le formulaire se remplit pour que vous confirmiez.'],
    ['Aperçus',
      'Tableau du jour', 'À faire, critique, en retard, actif + prochain', 'Un tableau montrant ce qui est dû aujourd’hui, critique, en retard et actif, plus la prochaine alarme.',
      'Statistiques', 'Totaux et tendances', 'Voyez les totaux, le compte de la semaine, votre heure la plus chargée et votre rappel le plus fréquent.',
      'Journal des alertes', 'Consigné automatiquement', 'Chaque rappel déclenché est consigné automatiquement pour revoir ce qui s’est déclenché.'],
    ['Système et réglages',
      'Mise à jour intégrée', 'Sans navigateur', 'Ouvrez Réglages → À propos et aide → Rechercher des mises à jour ; l’app télécharge et installe la nouvelle version elle-même.',
      'Sauvegarde', 'Enregistrer et restaurer', 'Dans Réglages → Sécurité et sauvegarde, enregistrez une sauvegarde chiffrée et restaurez-la ensuite sur tout appareil.',
      'Sync cloud', 'Google Drive chiffré', 'Dans l’écran de sauvegarde choisissez Google Drive, connectez-vous, mettez la même phrase de chiffrement sur chaque appareil et activez la sync auto ; les données sont chiffrées avant l’envoi.',
      'Verrou de l’app', 'PIN ou empreinte', 'Protégez l’app avec un PIN ou votre empreinte depuis Réglages → Sécurité et sauvegarde.',
      'Au calendrier', 'Exporter .ics ou partager', 'Exportez un rappel en fichier .ics pour l’ajouter au calendrier du téléphone, ou partagez-le en texte.',
      'Activation', 'Clé de licence universelle', 'Saisissez une fois la clé de licence universelle ; vous pouvez la désactiver plus tard pour la tester sur un autre appareil.'],
  ],
  'it': [
    ['Avvio rapido',
      'Tocca +', 'Apre il pannello del nuovo promemoria', 'Il pulsante + in basso apre il pannello del nuovo promemoria dove imposti tutto in un solo posto.',
      'Titolo', 'Cosa ricordare — o dettalo', 'Scrivi l’attività o tocca il microfono nel campo del titolo per dettarla.',
      'Scegli l’ora', 'Data e ora, hijri o gregoriano', 'Imposta data e ora; passa tra hijri e gregoriano col pulsante calendario nel selettore.',
      'Salva', 'Programmato subito', 'Tocca Salva e il promemoria è programmato subito e appare in Home nel suo gruppo orario.',
      'Aggiunta vocale', 'Di’ una frase in Home', 'Tocca il piccolo microfono in Home e di’ una frase intera; ora e attività vengono compilate da confermare.'],
    ['Tipi di promemoria',
      'Generale', 'Qualsiasi promemoria quotidiano', 'Il tipo predefinito per qualsiasi attività quotidiana che non rientra in una categoria speciale.',
      'Farmaco', 'Dosi e conteggio del ciclo', 'Aggiunge un campo dose e un conteggio opzionale, così l’app traccia le dosi rimanenti.',
      'Appuntamento', 'Con luogo e invito', 'Permette di allegare un luogo sulla mappa (link Google Maps) e un invito immagine o PDF.',
      'Occasione', 'Compleanni ed eventi — annuale', 'Ideale per compleanni ed eventi annuali; usa una ripetizione annuale per non dimenticarli.',
      'Bollette', 'Pagamenti ricorrenti', 'Per pagamenti ricorrenti; abbinalo a una ripetizione mensile per ogni ciclo.',
      'Viaggio', 'Viaggi e partenze', 'Per viaggi e partenze; aggiungi un pre-avviso per partire in tempo.',
      'Auto', 'Manutenzione e rinnovi', 'Per date di manutenzione e rinnovo documenti; usa una ripetizione annuale o personalizzata.'],
    ['Ora e ripetizione',
      'Ripeti', 'Una volta · giornaliero · settimanale · mensile · annuale', 'Scegli Una volta, Giornaliero, Settimanale (scegli i giorni), Mensile o Annuale nel selettore.',
      'Annuale hijri', 'Alla data hijri ogni anno', 'Si ripete alla stessa data hijri ogni anno, ideale per le occasioni islamiche.',
      'Ogni N giorni', 'Il tuo intervallo personalizzato', 'Scegli un intervallo proprio come ogni 3 o 10 giorni quando nessuna ripetizione standard va bene.',
      'Ciclo di farmaco', 'Il resto cala', 'Imposta il totale delle dosi; il resto cala a ogni orario programmato.',
      'Pre-avviso', '5 min / 15 min / ora / giorno prima', 'Ricevi un avviso anticipato 5 min, 15 min, un’ora o un giorno prima dell’orario reale.',
      'Posponi', '5–60 minuti dalla sveglia', 'Quando la sveglia suona, puoi posticiparla da 5 a 60 minuti dalla schermata di sveglia.'],
    ['Suono e urgenza',
      'Libreria suoni', 'Toni integrati e del dispositivo', 'Scegli toni integrati, suoni naturali morbidi o qualsiasi suono sul dispositivo, inclusi i toni Huawei.',
      'Alza il volume', 'Udibile in silenzioso o basso', 'Attivalo perché la sveglia alzi il volume da sola e sia udibile anche in silenzioso o basso.',
      'Critico crescente', 'Cresce se ignorato', 'Per i promemoria critici suono e vibrazione crescono ogni pochi secondi finché non rispondi.',
      'Modalità irrinunciabile', 'Risolvi una somma per chiudere', 'Attivala per dover risolvere una piccola somma prima di poter chiudere la sveglia.',
      'Sveglia affidabile', 'Chiusa, dopo riavvio, schermo intero', 'La sveglia suona anche ad app chiusa o dopo il riavvio, a schermo intero e offline.'],
    ['Personalizza e allega',
      'Colore proprio', 'Visibile sulla scheda', 'Scegli un colore dalla palette; appare sulla scheda per riconoscerlo a colpo d’occhio.',
      'Importanza', 'Normale o sveglia critica', 'Metti Normale per un avviso discreto, o Critico per aprire la sveglia a schermo intero con suono e vibrazione.',
      'Nota vocale', 'Allega una registrazione', 'Registra una breve nota vocale e allegala al promemoria per riascoltarla.',
      'Immagine / PDF', 'Invito o documento', 'Allega una foto di invito o un documento PDF, utile per appuntamenti ed eventi.',
      'Luogo', 'Link mappa o scegli un punto', 'Incolla un link Google Maps o scegli un punto, poi aprilo per il percorso quando suona il promemoria.',
      'Anteprima dal vivo', 'Vedila mentre scrivi', 'Vedi esattamente come apparirà e si leggerà il promemoria mentre lo scrivi.'],
    ['Vista e organizzazione',
      'Elenco o griglia', 'La scelta è salvata', 'Passa tra elenco e griglia di schede col pulsante della barra in alto; la scelta è memorizzata.',
      'Gruppi per tempo', 'Oggi / domani / questa settimana / dopo', 'I promemoria sono raggruppati e colorati per orario: oggi, domani, questa settimana e dopo.',
      'Cerca', 'Trova subito un promemoria', 'Tocca la lente e scrivi una parola per trovare un promemoria all’istante.',
      'Modelli', 'Promemoria pronti', 'Apri i modelli per partire da un promemoria pronto (farmaco, viaggio, auto, bolletta e altro) con un tocco.',
      'Creazione vocale', 'Parla; il modulo si compila', 'Di’ una frase naturale e il modulo si compila da solo da confermare.'],
    ['Approfondimenti',
      'Pannello di oggi', 'In scadenza, critico, scaduto, attivo + prossimo', 'Un pannello mostra cosa scade oggi, cosa è critico, scaduto e attivo, più la prossima sveglia.',
      'Statistiche', 'Totali e tendenze', 'Vedi totali, conteggio della settimana, la tua ora più intensa e il promemoria più frequente.',
      'Registro avvisi', 'Registrato in automatico', 'Ogni promemoria attivato è registrato automaticamente per rivedere ciò che è già scattato.'],
    ['Sistema e impostazioni',
      'Aggiornamento in-app', 'Senza browser', 'Apri Impostazioni → Info e aiuto → Cerca aggiornamenti; l’app scarica e installa la nuova versione da sola.',
      'Backup', 'Salva e ripristina', 'In Impostazioni → Sicurezza e backup, salva un backup cifrato e ripristinalo poi su qualsiasi dispositivo.',
      'Sync nel cloud', 'Google Drive cifrato', 'Nella schermata di backup scegli Google Drive, accedi, imposta la stessa passphrase su ogni dispositivo e attiva la sync automatica; i dati sono cifrati prima dell’invio.',
      'Blocco app', 'PIN o impronta', 'Proteggi l’app con un PIN o la tua impronta da Impostazioni → Sicurezza e backup.',
      'Al calendario', 'Esporta .ics o condividi', 'Esporta un promemoria come file .ics per aggiungerlo al calendario del telefono, o condividilo come testo.',
      'Attivazione', 'Chiave di licenza universale', 'Inserisci una volta la chiave di licenza universale; puoi disattivarla poi per provarla su un altro dispositivo.'],
  ],
  'id': [
    ['Mulai cepat',
      'Ketuk +', 'Membuka lembar pengingat baru', 'Tombol + di bawah membuka lembar pengingat baru tempat Anda mengatur semuanya di satu tempat.',
      'Judul', 'Apa yang diingat — atau diktekan', 'Ketik tugasnya, atau ketuk mikrofon di kolom judul untuk mendiktekannya.',
      'Pilih waktu', 'Tanggal dan jam, Hijriah atau Masehi', 'Atur tanggal dan jam; ganti antara Hijriah dan Masehi dengan tombol kalender di pemilih.',
      'Simpan', 'Langsung dijadwalkan', 'Ketuk Simpan dan pengingat langsung dijadwalkan serta tampil di Beranda dalam grup waktunya.',
      'Tambah suara', 'Ucapkan kalimat di Beranda', 'Ketuk tombol mik kecil di Beranda dan ucapkan kalimat utuh; waktu dan tugas terisi untuk dikonfirmasi.'],
    ['Jenis pengingat',
      'Umum', 'Pengingat harian apa pun', 'Jenis bawaan untuk tugas harian apa pun yang tidak masuk kategori khusus.',
      'Obat', 'Dosis dan hitungan kursus', 'Menambah kolom dosis dan hitungan kursus opsional, agar aplikasi melacak sisa dosis.',
      'Janji temu', 'Dengan lokasi dan undangan', 'Memungkinkan melampirkan lokasi peta (tautan Google Maps) dan undangan gambar atau PDF.',
      'Acara', 'Ulang tahun dan acara — tahunan', 'Cocok untuk ulang tahun dan acara tahunan; bawaannya pengulangan tahunan.',
      'Tagihan', 'Pembayaran berulang', 'Untuk pembayaran berulang; pasangkan dengan pengulangan bulanan tiap siklus.',
      'Perjalanan', 'Perjalanan dan keberangkatan', 'Untuk perjalanan dan keberangkatan; tambah pra-peringatan agar berangkat tepat waktu.',
      'Mobil', 'Servis dan perpanjangan', 'Untuk tanggal servis dan perpanjangan dokumen; gunakan pengulangan tahunan atau kustom.'],
    ['Waktu & ulang',
      'Ulangi', 'Sekali · harian · mingguan · bulanan · tahunan', 'Pilih Sekali, Harian, Mingguan (pilih hari), Bulanan atau Tahunan di pemilih.',
      'Tahunan Hijriah', 'Pada tanggal Hijriah tiap tahun', 'Berulang pada tanggal Hijriah yang sama tiap tahun, ideal untuk acara Islam.',
      'Tiap N hari', 'Interval kustom Anda', 'Pilih interval sendiri seperti tiap 3 atau 10 hari bila tak ada pengulangan standar yang cocok.',
      'Kursus obat', 'Sisa berkurang', 'Tetapkan total dosis; sisanya berkurang tiap waktu terjadwal.',
      'Pra-peringatan', '5 mnt / 15 mnt / jam / hari sebelum', 'Dapatkan peringatan dini 5 mnt, 15 mnt, satu jam atau satu hari sebelum waktu sebenarnya.',
      'Tunda', '5–60 menit dari alarm', 'Saat alarm berbunyi, tunda 5 sampai 60 menit dari layar alarm.'],
    ['Suara & urgensi',
      'Pustaka suara', 'Nada bawaan dan perangkat', 'Pilih nada bawaan, suara alam lembut, atau nada apa pun di perangkat termasuk nada Huawei.',
      'Naikkan volume', 'Terdengar saat senyap/pelan', 'Aktifkan agar alarm menaikkan volume sendiri dan terdengar meski ponsel senyap atau pelan.',
      'Kritis menanjak', 'Naik bila diabaikan', 'Untuk pengingat kritis, suara dan getaran naik tiap beberapa detik sampai Anda merespons.',
      'Mode tak terlewat', 'Selesaikan hitungan untuk menutup', 'Aktifkan agar harus menyelesaikan penjumlahan kecil sebelum alarm bisa ditutup.',
      'Alarm andal', 'Tertutup, usai restart, layar penuh', 'Alarm berbunyi meski aplikasi tertutup atau usai restart, layar penuh, dan offline.'],
    ['Sesuaikan & lampirkan',
      'Warna sendiri', 'Tampil di kartu', 'Pilih warna dari palet; tampil di kartu agar mudah dikenali sekilas.',
      'Kepentingan', 'Normal atau alarm kritis', 'Atur Normal untuk pemberitahuan tenang, atau Kritis untuk membuka alarm layar penuh dengan suara dan getaran.',
      'Catatan suara', 'Lampirkan rekaman', 'Rekam catatan suara singkat dan lampirkan ke pengingat untuk diputar nanti.',
      'Gambar / PDF', 'Undangan atau dokumen', 'Lampirkan foto undangan atau dokumen PDF, praktis untuk janji temu dan acara.',
      'Lokasi', 'Tautan peta atau pilih titik', 'Tempel tautan Google Maps atau pilih titik, lalu buka untuk rute saat pengingat berbunyi.',
      'Pratinjau langsung', 'Lihat saat mengetik', 'Lihat persis bagaimana pengingat tampil dan terbaca saat Anda mengetiknya.'],
    ['Tampil & atur',
      'Daftar atau kisi', 'Pilihan tersimpan', 'Ganti antara daftar dan kisi kartu dengan tombol bilah atas; pilihan Anda diingat.',
      'Grup waktu berwarna', 'Hari ini / besok / minggu ini / nanti', 'Pengingat dikelompokkan dan diberi warna menurut waktunya: hari ini, besok, minggu ini, dan nanti.',
      'Cari', 'Temukan pengingat cepat', 'Ketuk ikon cari dan ketik kata untuk menemukan pengingat seketika.',
      'Templat', 'Pengingat siap pakai', 'Buka templat untuk mulai dari pengingat siap pakai (obat, perjalanan, mobil, tagihan, dll.) dengan satu ketukan.',
      'Buat dengan suara', 'Bicara; formulir terisi', 'Ucapkan kalimat alami dan formulir terisi sendiri untuk dikonfirmasi.'],
    ['Wawasan',
      'Papan hari ini', 'Jatuh tempo, kritis, lewat, aktif + berikutnya', 'Papan yang menampilkan yang jatuh tempo hari ini, kritis, lewat dan aktif, plus alarm berikutnya.',
      'Statistik', 'Total dan pola', 'Lihat total, hitungan minggu ini, jam tersibuk Anda, dan pengingat tersering.',
      'Log notifikasi', 'Dicatat otomatis', 'Setiap pengingat yang berbunyi dicatat otomatis agar Anda bisa meninjau yang sudah lewat.'],
    ['Sistem & setelan',
      'Pembaruan dalam aplikasi', 'Tanpa peramban', 'Buka Setelan → Tentang & bantuan → Periksa pembaruan; aplikasi mengunduh dan memasang versi baru sendiri.',
      'Cadangan', 'Simpan dan pulihkan', 'Di Setelan → Keamanan & cadangan, simpan cadangan terenkripsi dan pulihkan nanti di perangkat mana pun.',
      'Sinkron awan', 'Google Drive terenkripsi', 'Di layar cadangan pilih Google Drive, masuk, atur frasa sandi enkripsi yang sama di tiap perangkat, dan aktifkan sinkron otomatis; data dienkripsi sebelum dikirim.',
      'Kunci aplikasi', 'PIN atau sidik jari', 'Lindungi aplikasi dengan PIN atau sidik jari dari Setelan → Keamanan & cadangan.',
      'Ke kalender', 'Ekspor .ics atau bagikan', 'Ekspor pengingat sebagai berkas .ics untuk ditambahkan ke kalender ponsel, atau bagikan sebagai teks.',
      'Aktivasi', 'Kunci lisensi universal', 'Masukkan kunci lisensi universal sekali untuk mengaktifkan; Anda bisa menonaktifkan nanti untuk mengujinya di perangkat lain.'],
  ],
  'ms': [
    ['Mula pantas',
      'Ketik +', 'Membuka helaian peringatan baharu', 'Butang + di bawah membuka helaian peringatan baharu tempat anda tetapkan semuanya di satu tempat.',
      'Tajuk', 'Apa yang diingat — atau sebut', 'Taip tugasnya, atau ketik mikrofon dalam medan tajuk untuk menyebutnya.',
      'Pilih masa', 'Tarikh dan masa, Hijrah atau Masihi', 'Tetapkan tarikh dan masa; tukar antara Hijrah dan Masihi dengan butang kalendar dalam pemilih.',
      'Simpan', 'Dijadualkan serta-merta', 'Ketik Simpan dan peringatan dijadualkan serta-merta serta dipapar di Utama dalam kumpulan masanya.',
      'Tambah suara', 'Sebut ayat di Utama', 'Ketik butang mik kecil di Utama dan sebut ayat penuh; masa dan tugas diisi untuk disahkan.'],
    ['Jenis peringatan',
      'Umum', 'Sebarang peringatan harian', 'Jenis lalai untuk sebarang tugas harian yang tidak masuk kategori khas.',
      'Ubat', 'Dos dan kiraan kursus', 'Menambah medan dos dan kiraan kursus pilihan, supaya apl menjejak baki dos.',
      'Temu janji', 'Dengan lokasi dan jemputan', 'Membolehkan lampiran lokasi peta (pautan Google Maps) dan jemputan imej atau PDF.',
      'Majlis', 'Hari lahir dan majlis — tahunan', 'Sesuai untuk hari lahir dan majlis tahunan; lalainya pengulangan tahunan.',
      'Bil', 'Bayaran berulang', 'Untuk bayaran berulang; gandingkan dengan pengulangan bulanan bagi setiap kitaran.',
      'Perjalanan', 'Perjalanan dan pelepasan', 'Untuk perjalanan dan pelepasan; tambah pra-amaran supaya bertolak tepat masa.',
      'Kereta', 'Servis dan pembaharuan', 'Untuk tarikh servis dan pembaharuan dokumen; guna pengulangan tahunan atau tersuai.'],
    ['Masa & ulang',
      'Ulang', 'Sekali · harian · mingguan · bulanan · tahunan', 'Pilih Sekali, Harian, Mingguan (pilih hari), Bulanan atau Tahunan dalam pemilih.',
      'Tahunan Hijrah', 'Pada tarikh Hijrah setiap tahun', 'Berulang pada tarikh Hijrah yang sama setiap tahun, sesuai untuk majlis Islam.',
      'Setiap N hari', 'Selang tersuai anda', 'Pilih selang sendiri seperti setiap 3 atau 10 hari apabila tiada pengulangan piawai sesuai.',
      'Kursus ubat', 'Baki berkurang', 'Tetapkan jumlah dos; bakinya berkurang pada setiap masa berjadual.',
      'Pra-amaran', '5 min / 15 min / jam / hari sebelum', 'Dapatkan amaran awal 5 min, 15 min, sejam atau sehari sebelum masa sebenar.',
      'Tunda', '5–60 minit dari penggera', 'Apabila penggera berbunyi, tunda 5 hingga 60 minit dari skrin penggera.'],
    ['Bunyi & desakan',
      'Pustaka bunyi', 'Nada terbina dan peranti', 'Pilih nada terbina, bunyi alam lembut, atau sebarang nada pada peranti termasuk nada Huawei.',
      'Naikkan kelantangan', 'Didengar ketika senyap/perlahan', 'Aktifkan supaya penggera menaikkan kelantangan sendiri dan didengar walau telefon senyap atau perlahan.',
      'Kritikal menaik', 'Naik jika diabaikan', 'Untuk peringatan kritikal, bunyi dan getaran naik setiap beberapa saat sehingga anda bertindak balas.',
      'Mod tak terlepas', 'Selesai kiraan untuk tutup', 'Aktifkan supaya perlu selesaikan tambah kecil sebelum penggera boleh ditutup.',
      'Penggera boleh harap', 'Tertutup, selepas but, skrin penuh', 'Penggera berbunyi walau apl ditutup atau selepas but, skrin penuh dan luar talian.'],
    ['Sesuaikan & lampir',
      'Warna sendiri', 'Pada kad', 'Pilih warna dari palet; ia muncul pada kad untuk dikenali sepintas lalu.',
      'Kepentingan', 'Biasa atau penggera kritikal', 'Tetapkan Biasa untuk makluman senyap, atau Kritikal untuk buka penggera skrin penuh dengan bunyi dan getaran.',
      'Nota suara', 'Lampirkan rakaman', 'Rakam nota suara ringkas dan lampirkan pada peringatan untuk dimainkan kemudian.',
      'Imej / PDF', 'Jemputan atau dokumen', 'Lampirkan foto jemputan atau dokumen PDF, berguna untuk temu janji dan majlis.',
      'Lokasi', 'Pautan peta atau pilih titik', 'Tampal pautan Google Maps atau pilih titik, kemudian buka untuk arah apabila peringatan berbunyi.',
      'Pratonton langsung', 'Lihat sambil menaip', 'Lihat tepat bagaimana peringatan kelihatan dan dibaca sambil anda menaipnya.'],
    ['Papar & susun',
      'Senarai atau grid', 'Pilihan disimpan', 'Tukar antara senarai dan grid kad dengan butang bar atas; pilihan anda diingati.',
      'Kumpulan masa berwarna', 'Hari ini / esok / minggu ini / kemudian', 'Peringatan dikumpul dan diwarnakan ikut masa: hari ini, esok, minggu ini dan kemudian.',
      'Cari', 'Cari peringatan pantas', 'Ketik ikon cari dan taip perkataan untuk cari peringatan serta-merta.',
      'Templat', 'Peringatan sedia', 'Buka templat untuk mula dari peringatan sedia (ubat, perjalanan, kereta, bil dll.) dengan satu ketik.',
      'Cipta dengan suara', 'Sebut; borang diisi', 'Sebut ayat semula jadi dan borang mengisi sendiri untuk disahkan.'],
    ['Wawasan',
      'Papan hari ini', 'Tiba, kritikal, lewat, aktif + seterusnya', 'Papan yang menunjukkan yang tiba hari ini, kritikal, lewat dan aktif, serta penggera seterusnya.',
      'Statistik', 'Jumlah dan corak', 'Lihat jumlah, kiraan minggu ini, waktu paling sibuk anda dan peringatan paling kerap.',
      'Log pemberitahuan', 'Direkod automatik', 'Setiap peringatan yang berbunyi direkod automatik supaya anda boleh semak yang telah berlalu.'],
    ['Sistem & tetapan',
      'Kemas kini dalam apl', 'Tanpa pelayar', 'Buka Tetapan → Perihal & bantuan → Semak kemas kini; apl memuat turun dan memasang versi baharu sendiri.',
      'Sandaran', 'Simpan dan pulihkan', 'Di Tetapan → Keselamatan & sandaran, simpan sandaran tersulit dan pulihkan kemudian pada mana-mana peranti.',
      'Segerak awan', 'Google Drive tersulit', 'Di skrin sandaran pilih Google Drive, log masuk, tetapkan frasa laluan sulit yang sama pada setiap peranti, dan hidupkan auto-segerak; data disulitkan sebelum dihantar.',
      'Kunci apl', 'PIN atau cap jari', 'Lindungi apl dengan PIN atau cap jari dari Tetapan → Keselamatan & sandaran.',
      'Ke kalendar', 'Eksport .ics atau kongsi', 'Eksport peringatan sebagai fail .ics untuk ditambah ke kalendar telefon, atau kongsi sebagai teks.',
      'Pengaktifan', 'Kunci lesen universal', 'Masukkan kunci lesen universal sekali untuk mengaktifkan; anda boleh nyahaktif kemudian untuk mengujinya pada peranti lain.'],
  ],
  'fil': [
    ['Mabilis na simula',
      'Pindutin ang +', 'Bubuksan ang sheet ng bagong paalala', 'Ang + sa ibaba ay nagbubukas ng sheet ng bagong paalala kung saan itinatakda mo ang lahat sa isang lugar.',
      'Pamagat', 'Ano ang aalalahanin — o idikta', 'I-type ang gawain, o pindutin ang mikropono sa loob ng pamagat upang idikta ito.',
      'Pumili ng oras', 'Petsa at oras, Hijri o Gregorian', 'Itakda ang petsa at oras; magpalit ng Hijri at Gregorian gamit ang toggle ng kalendaryo sa picker.',
      'I-save', 'Naka-iskedyul agad', 'Pindutin ang I-save at agad na naka-iskedyul ang paalala at lumalabas sa Home sa grupo nito ng oras.',
      'Idagdag sa boses', 'Magsalita sa Home', 'Pindutin ang maliit na mik sa Home at magsalita ng buong pangungusap; mapupunan ang oras at gawain para kumpirmahin.'],
    ['Uri ng paalala',
      'Pangkalahatan', 'Anumang pang-araw-araw', 'Ang default na uri para sa anumang pang-araw-araw na gawain na walang espesyal na kategorya.',
      'Gamot', 'Dosis at bilang ng kurso', 'Nagdaragdag ng field ng dosis at opsyonal na bilang, para subaybayan ng app ang natitirang dosis.',
      'Appointment', 'May lokasyon at imbitasyon', 'Pinapayagang maglakip ng lokasyon sa mapa (Google Maps link) at imbitasyong larawan o PDF.',
      'Okasyon', 'Kaarawan at okasyon — taunan', 'Mainam para sa kaarawan at taunang okasyon; default na taunang pag-ulit.',
      'Mga bill', 'Paulit-ulit na bayad', 'Para sa paulit-ulit na bayad; ipares sa buwanang pag-ulit kada siklo.',
      'Biyahe', 'Biyahe at pag-alis', 'Para sa biyahe at pag-alis; magdagdag ng paunang abiso para umalis nang maaga.',
      'Kotse', 'Serbisyo at renewal', 'Para sa petsa ng serbisyo at renewal ng dokumento; gumamit ng taunan o pasadyang pag-ulit.'],
    ['Oras at ulit',
      'Ulitin', 'Isahan · araw-araw · lingguhan · buwanan · taunan', 'Pumili ng Isahan, Araw-araw, Lingguhan (piliin ang araw), Buwanan o Taunan sa picker.',
      'Taunang Hijri', 'Sa petsang Hijri kada taon', 'Inuulit sa parehong petsang Hijri kada taon, mainam para sa okasyong Islam.',
      'Tuwing N araw', 'Sarili mong agwat', 'Pumili ng sariling agwat tulad ng tuwing 3 o 10 araw kapag walang akmang karaniwang pag-ulit.',
      'Kurso ng gamot', 'Bumababa ang natitira', 'Itakda ang kabuuang dosis; bumababa ang natitira sa bawat nakatakdang oras.',
      'Paunang abiso', '5 min / 15 min / oras / araw bago', 'Kumuha ng maagang abiso 5 min, 15 min, isang oras o isang araw bago ang totoong oras.',
      'I-snooze', '5–60 minuto mula sa alarm', 'Kapag tumunog ang alarm, ipagpaliban ito ng 5 hanggang 60 minuto mula sa screen ng alarm.'],
    ['Tunog at pagkaapurahan',
      'Aklatan ng tunog', 'Mga tono at tono ng device', 'Pumili ng built-in na tono, malambot na tunog ng kalikasan, o anumang tono sa device kasama ang Huawei.',
      'Itaas ang volume', 'Naririnig kahit silent/mahina', 'I-on para itaas mismo ng alarm ang volume at marinig kahit silent o mahina ang telepono.',
      'Lumalakas na kritikal', 'Lumalakas kung binalewala', 'Sa kritikal na paalala, lumalakas ang tunog at vibration kada ilang segundo hanggang tumugon ka.',
      'Hindi-mapapalampas', 'Sagutin ang suma para isara', 'I-on para kailangang sagutin ang maliit na suma bago maisara ang alarm.',
      'Maaasahang alarm', 'Sarado, pagka-restart, full-screen', 'Tumutunog ang alarm kahit sarado ang app o pagka-restart, full-screen, at offline.'],
    ['I-customize at ilakip',
      'Sariling kulay', 'Sa card', 'Pumili ng kulay mula sa palette; lumalabas sa card para makilala agad.',
      'Kahalagahan', 'Normal o kritikal na alarm', 'Itakda ang Normal para sa tahimik na abiso, o Kritikal para buksan ang full-screen alarm na may tunog at vibration.',
      'Talang boses', 'Maglakip ng rekording', 'Mag-record ng maikling talang boses at ilakip sa paalala para i-play mamaya.',
      'Larawan / PDF', 'Imbitasyon o dokumento', 'Maglakip ng larawan ng imbitasyon o dokumentong PDF, kapaki-pakinabang sa appointment at okasyon.',
      'Lokasyon', 'Map link o pumili ng lugar', 'I-paste ang Google Maps link o pumili ng lugar, at buksan para sa direksyon kapag tumunog ang paalala.',
      'Live na preview', 'Tingnan habang nagta-type', 'Tingnan kung paano eksaktong lalabas at mababasa ang paalala habang tina-type mo.'],
    ['Tingnan at ayusin',
      'Listahan o grid', 'Naka-save ang pili', 'Magpalit ng listahan at grid ng card gamit ang button sa itaas; naaalala ang pili mo.',
      'Mga grupo ayon sa oras', 'Ngayon / bukas / ngayong linggo / mamaya', 'Pinagsama at kinulayan ang paalala ayon sa oras: ngayon, bukas, ngayong linggo at mamaya.',
      'Maghanap', 'Hanapin agad', 'Pindutin ang hanapin at mag-type ng salita para mahanap agad ang paalala.',
      'Mga template', 'Handang paalala', 'Buksan ang template para magsimula sa handang paalala (gamot, biyahe, kotse, bill at iba pa) sa isang pindot.',
      'Gumawa sa boses', 'Magsalita; mapupunan ang form', 'Magsalita ng natural na pangungusap at kusang mapupunan ang form para kumpirmahin.'],
    ['Mga insight',
      'Board ngayon', 'Nakatakda, kritikal, lampas, aktibo + susunod', 'Board na nagpapakita ng nakatakda ngayon, kritikal, lampas at aktibo, plus ang susunod na alarm.',
      'Estadistika', 'Mga kabuuan at pattern', 'Tingnan ang kabuuan, bilang ngayong linggo, pinakaabalang oras mo at pinakamadalas na paalala.',
      'Log ng abiso', 'Awtomatikong naitatala', 'Bawat tumunog na paalala ay awtomatikong naitatala para masuri ang naunang tumunog.'],
    ['Sistema at setting',
      'In-app update', 'Walang browser', 'Buksan ang Settings → Tungkol at tulong → Maghanap ng update; mismong ina-download at ini-install ng app ang bagong bersyon.',
      'Backup', 'I-save at ibalik', 'Sa Settings → Seguridad at backup, mag-save ng naka-encrypt na backup at ibalik mamaya sa anumang device.',
      'Cloud sync', 'Naka-encrypt na Google Drive', 'Sa screen ng backup piliin ang Google Drive, mag-sign in, itakda ang parehong encryption passphrase sa bawat device, at i-on ang auto-sync; naka-encrypt ang data bago umalis sa telepono.',
      'Lock ng app', 'PIN o fingerprint', 'Protektahan ang app ng PIN o fingerprint mula sa Settings → Seguridad at backup.',
      'Idagdag sa kalendaryo', 'I-export ang .ics o ibahagi', 'I-export ang paalala bilang .ics file para idagdag sa kalendaryo ng telepono, o ibahagi bilang teksto.',
      'Activation', 'Universal license key', 'Ilagay ang universal license key nang isang beses para i-activate; maaari mong i-deactivate mamaya para subukan sa ibang device.'],
  ],
  'hi': [
    ['तेज़ शुरुआत',
      '+ दबाएँ', 'नया रिमाइंडर शीट खोलता है', 'नीचे का + बटन नया रिमाइंडर शीट खोलता है जहाँ आप सब कुछ एक ही जगह सेट करते हैं।',
      'शीर्षक', 'क्या याद रखना — या बोलें', 'काम टाइप करें, या शीर्षक फ़ील्ड में माइक दबाकर उसे बोलें।',
      'समय चुनें', 'तारीख और समय, हिजरी या ग्रेगोरियन', 'तारीख और समय सेट करें; पिकर में कैलेंडर बटन से हिजरी और ग्रेगोरियन के बीच बदलें।',
      'सहेजें', 'तुरंत शेड्यूल होता है', 'सहेजें दबाएँ और रिमाइंडर तुरंत शेड्यूल होकर होम पर अपने समय-समूह में दिखता है।',
      'वॉइस से जोड़ें', 'होम पर एक वाक्य बोलें', 'होम पर छोटा माइक बटन दबाएँ और पूरा वाक्य बोलें; समय और काम भर जाते हैं ताकि आप पुष्टि करें।'],
    ['रिमाइंडर के प्रकार',
      'सामान्य', 'कोई भी रोज़ाना रिमाइंडर', 'किसी भी रोज़ाना काम के लिए डिफ़ॉल्ट प्रकार जो किसी विशेष श्रेणी में नहीं आता।',
      'दवा', 'खुराक और कोर्स गिनती', 'खुराक फ़ील्ड और वैकल्पिक कोर्स गिनती जोड़ता है, ताकि ऐप बची खुराक पर नज़र रखे।',
      'अपॉइंटमेंट', 'स्थान और निमंत्रण के साथ', 'नक्शे का स्थान (Google Maps लिंक) और इमेज या PDF निमंत्रण जोड़ने देता है।',
      'अवसर', 'जन्मदिन और अवसर — सालाना', 'जन्मदिन और सालाना अवसरों के लिए सर्वोत्तम; डिफ़ॉल्ट रूप से सालाना दोहराव।',
      'बिल', 'दोहराने वाले भुगतान', 'दोहराने वाले भुगतानों के लिए; हर चक्र की याद हेतु मासिक दोहराव से जोड़ें।',
      'यात्रा', 'यात्रा और प्रस्थान', 'यात्रा और प्रस्थान के लिए; समय पर निकलने हेतु पूर्व-सूचना जोड़ें।',
      'कार', 'सर्विस और नवीनीकरण', 'सर्विस तिथि और दस्तावेज़ नवीनीकरण के लिए; सालाना या कस्टम दोहराव चुनें।'],
    ['समय और दोहराव',
      'दोहराएँ', 'एक बार · रोज़ · साप्ताहिक · मासिक · सालाना', 'पिकर से एक बार, रोज़, साप्ताहिक (दिन चुनें), मासिक या सालाना चुनें।',
      'सालाना हिजरी', 'हर साल हिजरी तारीख पर', 'हर साल उसी हिजरी (चंद्र) तारीख पर दोहराता है, इस्लामी अवसरों के लिए आदर्श।',
      'हर N दिन', 'आपका कस्टम अंतराल', 'जब कोई मानक दोहराव फिट न हो तो हर 3 या 10 दिन जैसा अपना अंतराल चुनें।',
      'दवा कोर्स', 'शेष घटता है', 'कुल खुराक तय करें; हर शेड्यूल समय पर शेष गिनती घटती है।',
      'पूर्व-सूचना', '5 मि / 15 मि / घंटा / दिन पहले', 'वास्तविक समय से 5 मि, 15 मि, एक घंटा या एक दिन पहले अग्रिम सूचना पाएँ।',
      'स्नूज़', 'अलार्म स्क्रीन से 5–60 मिनट', 'अलार्म बजने पर उसे अलार्म स्क्रीन से 5 से 60 मिनट तक टालें।'],
    ['ध्वनि और तात्कालिकता',
      'ध्वनि लाइब्रेरी', 'अंतर्निहित और डिवाइस टोन', 'अंतर्निहित टोन, मुलायम प्राकृतिक ध्वनियाँ, या अपने डिवाइस की कोई भी टोन (हुवावे सहित) चुनें।',
      'आवाज़ बढ़ाएँ', 'साइलेंट/कम पर सुनाई', 'इसे चालू करें ताकि अलार्म खुद आवाज़ बढ़ाए और फ़ोन साइलेंट या कम होने पर भी सुनाई दे।',
      'बढ़ता क्रिटिकल', 'अनदेखा करने पर बढ़ता', 'क्रिटिकल रिमाइंडर में हर कुछ सेकंड में ध्वनि व कंपन बढ़ते हैं जब तक आप प्रतिक्रिया न दें।',
      'न चूकने वाला मोड', 'बंद करने से पहले जोड़ हल करें', 'इसे चालू करें ताकि अलार्म बंद करने से पहले छोटा जोड़ हल करना पड़े।',
      'भरोसेमंद अलार्म', 'बंद, रीस्टार्ट पर, फुल-स्क्रीन', 'ऐप बंद होने या रीस्टार्ट के बाद भी अलार्म बजता है, फुल-स्क्रीन और बिना इंटरनेट।'],
    ['अनुकूलित करें व जोड़ें',
      'अपना रंग', 'कार्ड पर दिखे', 'पैलेट से रंग चुनें; यह कार्ड पर दिखता है ताकि एक नज़र में पहचानें।',
      'महत्व', 'सामान्य या क्रिटिकल अलार्म', 'शांत सूचना के लिए सामान्य, या ध्वनि व कंपन के साथ फुल-स्क्रीन अलार्म खोलने हेतु क्रिटिकल चुनें।',
      'वॉइस नोट', 'एक रिकॉर्डिंग जोड़ें', 'छोटा वॉइस नोट रिकॉर्ड कर रिमाइंडर में जोड़ें ताकि बाद में चलाएँ।',
      'इमेज / PDF', 'निमंत्रण या दस्तावेज़', 'निमंत्रण फ़ोटो या PDF दस्तावेज़ जोड़ें, अपॉइंटमेंट और अवसरों के लिए उपयोगी।',
      'स्थान', 'नक्शा लिंक या जगह चुनें', 'Google Maps लिंक पेस्ट करें या जगह चुनें, फिर रिमाइंडर बजने पर दिशा हेतु खोलें।',
      'लाइव पूर्वावलोकन', 'टाइप करते देखें', 'देखें कि टाइप करते समय रिमाइंडर कैसा दिखेगा और पढ़ा जाएगा।'],
    ['देखें और व्यवस्थित करें',
      'सूची या ग्रिड', 'चयन सहेजा जाता है', 'ऊपर के बटन से सूची और कार्ड ग्रिड के बीच बदलें; आपका चयन याद रहता है।',
      'रंगीन समय-समूह', 'आज / कल / इस सप्ताह / बाद में', 'रिमाइंडर बजने के समय अनुसार समूहित व रंगीन: आज, कल, इस सप्ताह और बाद में।',
      'खोज', 'कोई भी रिमाइंडर तेज़ी से', 'खोज आइकन दबाएँ और कोई शब्द टाइप कर रिमाइंडर तुरंत ढूँढें।',
      'टेम्पलेट', 'तैयार रिमाइंडर', 'एक टैप में तैयार रिमाइंडर (दवा, यात्रा, कार, बिल आदि) से शुरू करने हेतु टेम्पलेट खोलें।',
      'वॉइस से बनाएँ', 'बोलें; फ़ॉर्म भर जाता', 'स्वाभाविक वाक्य बोलें और फ़ॉर्म खुद भर जाता है ताकि आप पुष्टि करें।'],
    ['अंतर्दृष्टि',
      'आज का बोर्ड', 'देय, क्रिटिकल, विलंबित, सक्रिय + अगला', 'एक बोर्ड जो आज देय, क्रिटिकल, विलंबित और सक्रिय दिखाता है, साथ ही अगला अलार्म।',
      'आँकड़े', 'कुल और पैटर्न', 'कुल, इस सप्ताह की गिनती, आपका व्यस्ततम घंटा और सबसे बार-बार रिमाइंडर देखें।',
      'सूचना लॉग', 'अपने आप दर्ज', 'हर बजा रिमाइंडर अपने आप लॉग में दर्ज होता है ताकि आप पिछले की समीक्षा करें।'],
    ['सिस्टम और सेटिंग्स',
      'इन-ऐप अपडेट', 'बिना ब्राउज़र', 'सेटिंग्स → बारे में व मदद → अपडेट जांचें खोलें; ऐप खुद नई वर्शन डाउनलोड कर इंस्टॉल करता है।',
      'बैकअप', 'सहेजें और पुनर्स्थापित', 'सेटिंग्स → सुरक्षा व बैकअप में, एन्क्रिप्टेड बैकअप सहेजें और बाद में किसी भी डिवाइस पर पुनर्स्थापित करें।',
      'क्लाउड सिंक', 'एन्क्रिप्टेड Google Drive', 'बैकअप स्क्रीन में Google Drive चुनें, साइन इन करें, हर डिवाइस पर वही एन्क्रिप्शन पासफ़्रेज़ सेट करें, और ऑटो-सिंक चालू करें; डेटा फ़ोन छोड़ने से पहले एन्क्रिप्ट होता है।',
      'ऐप लॉक', 'PIN या फिंगरप्रिंट', 'सेटिंग्स → सुरक्षा व बैकअप से ऐप को PIN या फिंगरप्रिंट से सुरक्षित करें।',
      'कैलेंडर में जोड़ें', '.ics निर्यात या साझा', 'किसी रिमाइंडर को .ics फ़ाइल के रूप में निर्यात कर फ़ोन कैलेंडर में जोड़ें, या टेक्स्ट के रूप में साझा करें।',
      'सक्रियण', 'यूनिवर्सल लाइसेंस कुंजी', 'सक्रिय करने हेतु यूनिवर्सल लाइसेंस कुंजी एक बार डालें; बाद में दूसरे डिवाइस पर परखने हेतु निष्क्रिय कर सकते हैं।'],
  ],
  'bn': [
    ['দ্রুত শুরু',
      '+ চাপুন', 'নতুন রিমাইন্ডার শিট খোলে', 'নিচের + বোতাম নতুন রিমাইন্ডার শিট খোলে যেখানে আপনি সব কিছু এক জায়গায় ঠিক করেন।',
      'শিরোনাম', 'কী মনে রাখবেন — বা বলুন', 'কাজটি টাইপ করুন, বা শিরোনাম ঘরে মাইক চেপে তা বলুন।',
      'সময় বাছুন', 'তারিখ ও সময়, হিজরি বা গ্রেগরিয়ান', 'তারিখ ও সময় ঠিক করুন; পিকারে ক্যালেন্ডার বোতামে হিজরি ও গ্রেগরিয়ানের মধ্যে বদলান।',
      'সংরক্ষণ', 'সঙ্গে সঙ্গে শিডিউল হয়', 'সংরক্ষণ চাপুন, রিমাইন্ডার সঙ্গে সঙ্গে শিডিউল হয়ে হোমে তার সময়-গ্রুপে দেখায়।',
      'ভয়েসে যোগ', 'হোমে একটি বাক্য বলুন', 'হোমে ছোট মাইক বোতাম চেপে পুরো বাক্য বলুন; সময় ও কাজ পূরণ হয় নিশ্চিত করার জন্য।'],
    ['রিমাইন্ডারের ধরন',
      'সাধারণ', 'যেকোনো দৈনন্দিন রিমাইন্ডার', 'যেকোনো দৈনন্দিন কাজের জন্য ডিফল্ট ধরন যা বিশেষ বিভাগে পড়ে না।',
      'ওষুধ', 'ডোজ ও কোর্স গণনা', 'একটি ডোজ ঘর ও ঐচ্ছিক কোর্স গণনা যোগ করে, যাতে অ্যাপ বাকি ডোজ হিসাব রাখে।',
      'অ্যাপয়েন্টমেন্ট', 'স্থান ও আমন্ত্রণসহ', 'মানচিত্রের স্থান (Google Maps লিঙ্ক) ও ছবি বা PDF আমন্ত্রণ যুক্ত করতে দেয়।',
      'অনুষ্ঠান', 'জন্মদিন ও অনুষ্ঠান — বার্ষিক', 'জন্মদিন ও বার্ষিক অনুষ্ঠানের জন্য সেরা; ডিফল্ট বার্ষিক পুনরাবৃত্তি।',
      'বিল', 'পুনরাবৃত্ত পরিশোধ', 'পুনরাবৃত্ত পরিশোধের জন্য; প্রতি চক্রে মনে করাতে মাসিক পুনরাবৃত্তির সাথে যুক্ত করুন।',
      'ভ্রমণ', 'ভ্রমণ ও প্রস্থান', 'ভ্রমণ ও প্রস্থানের জন্য; সময়মতো বের হতে আগাম সতর্কতা যোগ করুন।',
      'গাড়ি', 'সার্ভিস ও নবায়ন', 'সার্ভিস তারিখ ও নথি নবায়নের জন্য; বার্ষিক বা কাস্টম পুনরাবৃত্তি ব্যবহার করুন।'],
    ['সময় ও পুনরাবৃত্তি',
      'পুনরাবৃত্তি', 'একবার · দৈনিক · সাপ্তাহিক · মাসিক · বার্ষিক', 'পিকার থেকে একবার, দৈনিক, সাপ্তাহিক (দিন বাছুন), মাসিক বা বার্ষিক বাছুন।',
      'বার্ষিক হিজরি', 'প্রতি বছর হিজরি তারিখে', 'প্রতি বছর একই হিজরি (চান্দ্র) তারিখে পুনরাবৃত্ত হয়, ইসলামি অনুষ্ঠানের জন্য আদর্শ।',
      'প্রতি N দিন', 'আপনার কাস্টম ব্যবধান', 'কোনো মানক পুনরাবৃত্তি না মিললে প্রতি 3 বা 10 দিনের মতো নিজের ব্যবধান বাছুন।',
      'ওষুধ কোর্স', 'বাকি কমে', 'মোট ডোজ ঠিক করুন; প্রতিটি নির্ধারিত সময়ে বাকি সংখ্যা কমে।',
      'আগাম সতর্কতা', '5 মি / 15 মি / ঘণ্টা / দিন আগে', 'প্রকৃত সময়ের 5 মি, 15 মি, এক ঘণ্টা বা এক দিন আগে আগাম সতর্কতা পান।',
      'স্নুজ', 'অ্যালার্ম স্ক্রিন থেকে 5–60 মিনিট', 'অ্যালার্ম বাজলে অ্যালার্ম স্ক্রিন থেকে 5 থেকে 60 মিনিট পিছিয়ে দিন।'],
    ['শব্দ ও জরুরিতা',
      'সাউন্ড লাইব্রেরি', 'অন্তর্নির্মিত ও ডিভাইস টোন', 'অন্তর্নির্মিত টোন, নরম প্রাকৃতিক শব্দ, বা আপনার ডিভাইসের যেকোনো টোন (হুয়াওয়েসহ) বাছুন।',
      'ভলিউম বাড়ান', 'সাইলেন্ট/নিচুতেও শোনা যায়', 'এটি চালু করুন যাতে অ্যালার্ম নিজে ভলিউম বাড়ায় এবং ফোন সাইলেন্ট বা নিচু থাকলেও শোনা যায়।',
      'বাড়তে থাকা ক্রিটিক্যাল', 'উপেক্ষা করলে বাড়ে', 'ক্রিটিক্যাল রিমাইন্ডারে প্রতি কয়েক সেকেন্ডে শব্দ ও কম্পন বাড়ে যতক্ষণ না সাড়া দেন।',
      'মিস-না মোড', 'বন্ধের আগে যোগফল মেলান', 'এটি চালু করুন যাতে অ্যালার্ম বন্ধের আগে ছোট যোগফল মেলাতে হয়।',
      'নির্ভরযোগ্য অ্যালার্ম', 'বন্ধ, রিস্টার্টে, ফুল-স্ক্রিন', 'অ্যাপ বন্ধ থাকলে বা রিস্টার্টের পরেও অ্যালার্ম বাজে, ফুল-স্ক্রিন ও অফলাইন।'],
    ['কাস্টমাইজ ও সংযুক্ত',
      'নিজস্ব রং', 'কার্ডে দেখায়', 'প্যালেট থেকে রং বাছুন; এটি কার্ডে দেখায় যাতে এক নজরে চেনা যায়।',
      'গুরুত্ব', 'সাধারণ বা ক্রিটিক্যাল অ্যালার্ম', 'শান্ত বিজ্ঞপ্তির জন্য সাধারণ, বা শব্দ ও কম্পনসহ ফুল-স্ক্রিন অ্যালার্ম খুলতে ক্রিটিক্যাল বাছুন।',
      'ভয়েস নোট', 'একটি রেকর্ডিং সংযুক্ত', 'ছোট ভয়েস নোট রেকর্ড করে রিমাইন্ডারে যুক্ত করুন পরে চালানোর জন্য।',
      'ছবি / PDF', 'আমন্ত্রণ বা নথি', 'আমন্ত্রণ ছবি বা PDF নথি যুক্ত করুন, অ্যাপয়েন্টমেন্ট ও অনুষ্ঠানে কাজে লাগে।',
      'অবস্থান', 'মানচিত্র লিঙ্ক বা স্থান বাছুন', 'Google Maps লিঙ্ক পেস্ট করুন বা স্থান বাছুন, পরে রিমাইন্ডার বাজলে দিকনির্দেশের জন্য খুলুন।',
      'লাইভ প্রিভিউ', 'টাইপ করার সময় দেখুন', 'টাইপ করার সময় রিমাইন্ডার কেমন দেখাবে ও পড়া যাবে তা দেখুন।'],
    ['দেখা ও সাজানো',
      'তালিকা বা গ্রিড', 'পছন্দ সংরক্ষিত', 'উপরের বোতামে তালিকা ও কার্ড গ্রিডের মধ্যে বদলান; আপনার পছন্দ মনে রাখা হয়।',
      'রঙিন সময়-গ্রুপ', 'আজ / আগামীকাল / এ সপ্তাহ / পরে', 'রিমাইন্ডার বাজার সময় অনুযায়ী গ্রুপ ও রঙিন: আজ, আগামীকাল, এ সপ্তাহ ও পরে।',
      'অনুসন্ধান', 'যেকোনো রিমাইন্ডার দ্রুত', 'অনুসন্ধান আইকন চেপে একটি শব্দ টাইপ করে রিমাইন্ডার সঙ্গে সঙ্গে খুঁজুন।',
      'টেমপ্লেট', 'প্রস্তুত রিমাইন্ডার', 'এক চাপে প্রস্তুত রিমাইন্ডার (ওষুধ, ভ্রমণ, গাড়ি, বিল ইত্যাদি) থেকে শুরু করতে টেমপ্লেট খুলুন।',
      'ভয়েসে তৈরি', 'বলুন; ফর্ম পূরণ হয়', 'স্বাভাবিক বাক্য বলুন এবং ফর্ম নিজে পূরণ হয় নিশ্চিত করার জন্য।'],
    ['অন্তর্দৃষ্টি',
      'আজকের বোর্ড', 'বাকি, ক্রিটিক্যাল, বিলম্বিত, সক্রিয় + পরবর্তী', 'একটি বোর্ড যা আজ বাকি, ক্রিটিক্যাল, বিলম্বিত ও সক্রিয় দেখায়, সঙ্গে পরবর্তী অ্যালার্ম।',
      'পরিসংখ্যান', 'মোট ও প্যাটার্ন', 'মোট, এ সপ্তাহের গণনা, আপনার ব্যস্ততম সময় ও সবচেয়ে ঘন রিমাইন্ডার দেখুন।',
      'বিজ্ঞপ্তি লগ', 'স্বয়ংক্রিয় রেকর্ড', 'প্রতিটি বাজা রিমাইন্ডার স্বয়ংক্রিয়ভাবে লগে রেকর্ড হয় যাতে আগেরটি পর্যালোচনা করতে পারেন।'],
    ['সিস্টেম ও সেটিংস',
      'ইন-অ্যাপ আপডেট', 'ব্রাউজার ছাড়া', 'সেটিংস → সম্পর্কে ও সহায়তা → আপডেট দেখুন খুলুন; অ্যাপ নিজে নতুন সংস্করণ ডাউনলোড করে ইনস্টল করে।',
      'ব্যাকআপ', 'সংরক্ষণ ও পুনরুদ্ধার', 'সেটিংস → নিরাপত্তা ও ব্যাকআপে, এনক্রিপ্টেড ব্যাকআপ সংরক্ষণ করুন এবং পরে যেকোনো ডিভাইসে পুনরুদ্ধার করুন।',
      'ক্লাউড সিঙ্ক', 'এনক্রিপ্টেড Google Drive', 'ব্যাকআপ স্ক্রিনে Google Drive বাছুন, সাইন ইন করুন, প্রতি ডিভাইসে একই এনক্রিপশন পাসফ্রেজ দিন, এবং অটো-সিঙ্ক চালু করুন; ডেটা ফোন ছাড়ার আগে এনক্রিপ্ট হয়।',
      'অ্যাপ লক', 'PIN বা ফিঙ্গারপ্রিন্ট', 'সেটিংস → নিরাপত্তা ও ব্যাকআপ থেকে অ্যাপটি PIN বা ফিঙ্গারপ্রিন্ট দিয়ে সুরক্ষিত করুন।',
      'ক্যালেন্ডারে যোগ', '.ics রপ্তানি বা শেয়ার', 'কোনো রিমাইন্ডার .ics ফাইল হিসেবে রপ্তানি করে ফোন ক্যালেন্ডারে যোগ করুন, বা টেক্সট হিসেবে শেয়ার করুন।',
      'অ্যাক্টিভেশন', 'ইউনিভার্সাল লাইসেন্স কী', 'সক্রিয় করতে ইউনিভার্সাল লাইসেন্স কী একবার দিন; পরে অন্য ডিভাইসে পরখতে নিষ্ক্রিয় করতে পারেন।'],
  ],
  'fa': [
    ['شروع سریع',
      'روی + بزن', 'برگه یادآور جدید را باز می‌کند', 'دکمه + پایین، برگه یادآور جدید را باز می‌کند که همه چیز را در یک جا تنظیم می‌کنی.',
      'عنوان', 'چه چیزی یادآوری شود — یا بگو', 'کار را تایپ کن، یا میکروفون داخل عنوان را بزن تا آن را بگویی.',
      'زمان را انتخاب کن', 'تاریخ و ساعت، هجری یا میلادی', 'تاریخ و ساعت را تنظیم کن؛ با دکمه تقویم در انتخابگر بین هجری و میلادی جابه‌جا شو.',
      'ذخیره', 'فوری زمان‌بندی می‌شود', 'ذخیره را بزن، یادآور فوری زمان‌بندی و در خانه در گروه زمانی‌اش نمایش داده می‌شود.',
      'افزودن صوتی', 'در خانه یک جمله بگو', 'دکمه میکروفون کوچک در خانه را بزن و جمله کامل بگو؛ زمان و کار برای تأیید پر می‌شود.'],
    ['انواع یادآور',
      'عمومی', 'هر یادآور روزمره', 'نوع پیش‌فرض برای هر کار روزمره که در دسته خاصی نمی‌گنجد.',
      'دارو', 'دوزها و شمارش دوره', 'یک فیلد دوز و شمارش دوره اختیاری اضافه می‌کند تا برنامه دوزهای باقی‌مانده را پیگیری کند.',
      'قرار', 'با مکان و دعوت‌نامه', 'امکان پیوست مکان روی نقشه (لینک گوگل‌مپ) و دعوت‌نامه تصویری یا PDF را می‌دهد.',
      'مناسبت', 'تولدها و مناسبت‌ها — سالانه', 'برای تولدها و مناسبت‌های سالانه عالی است؛ پیش‌فرض تکرار سالانه.',
      'قبوض', 'پرداخت‌های تکراری', 'برای پرداخت‌های تکراری؛ آن را با تکرار ماهانه برای هر دوره ترکیب کن.',
      'سفر', 'سفرها و پروازها', 'برای سفرها و پروازها؛ یک هشدار پیش‌هنگام بگذار تا به‌موقع راه بیفتی.',
      'خودرو', 'سرویس و تمدیدها', 'برای تاریخ سرویس و تمدید مدارک؛ از تکرار سالانه یا سفارشی استفاده کن.'],
    ['زمان و تکرار',
      'تکرار', 'یک‌بار · روزانه · هفتگی · ماهانه · سالانه', 'از انتخابگر یک‌بار، روزانه، هفتگی (روزها را انتخاب کن)، ماهانه یا سالانه را برگزین.',
      'سالانه هجری', 'هر سال در تاریخ هجری', 'هر سال در همان تاریخ هجری (قمری) تکرار می‌شود، مناسب مناسبت‌های اسلامی.',
      'هر N روز', 'بازه سفارشی خودت', 'وقتی هیچ تکرار استانداردی مناسب نیست، بازه‌ای مثل هر ۳ یا ۱۰ روز انتخاب کن.',
      'دوره دارو', 'باقی‌مانده کم می‌شود', 'تعداد کل دوز را تعیین کن؛ باقی‌مانده با هر زمان زمان‌بندی‌شده کم می‌شود.',
      'هشدار پیش‌هنگام', '۵د / ۱۵د / ساعت / روز قبل', 'هشدار زودهنگام ۵ دقیقه، ۱۵ دقیقه، یک ساعت یا یک روز پیش از زمان واقعی بگیر.',
      'تعویق', '۵ تا ۶۰ دقیقه از صفحه زنگ', 'وقتی زنگ به صدا درآمد، آن را از صفحه زنگ ۵ تا ۶۰ دقیقه به تعویق بینداز.'],
    ['صدا و فوریت',
      'کتابخانه صداها', 'آهنگ‌های داخلی و دستگاه', 'آهنگ‌های داخلی، صداهای ملایم طبیعت، یا هر آهنگ روی دستگاهت از جمله هواوی را انتخاب کن.',
      'بالا بردن صدا', 'در بی‌صدا/کم شنیده می‌شود', 'روشنش کن تا زنگ خودش صدا را بالا ببرد و حتی در حالت بی‌صدا یا کم شنیده شود.',
      'بحرانی فزاینده', 'با بی‌توجهی بیشتر می‌شود', 'برای یادآورهای بحرانی، صدا و لرزش هر چند ثانیه بیشتر می‌شود تا واکنش نشان دهی.',
      'حالت از‌دست‌نرفتنی', 'پیش از بستن یک جمع را حل کن', 'روشنش کن تا پیش از آنکه زنگ بسته شود، یک جمع کوچک را حل کنی.',
      'زنگ مطمئن', 'بسته، پس از ری‌استارت، تمام‌صفحه', 'زنگ حتی با برنامه بسته یا پس از ری‌استارت به صدا درمی‌آید، تمام‌صفحه و آفلاین.'],
    ['شخصی‌سازی و پیوست',
      'رنگ دلخواه', 'روی کارت', 'رنگی از پالت انتخاب کن؛ روی کارت ظاهر می‌شود تا با یک نگاه بشناسی‌اش.',
      'اهمیت', 'عادی یا زنگ بحرانی', 'برای اعلان آرام عادی، یا برای باز شدن زنگ تمام‌صفحه با صدا و لرزش بحرانی را برگزین.',
      'یادداشت صوتی', 'یک ضبط پیوست کن', 'یک یادداشت صوتی کوتاه ضبط و به یادآور پیوست کن تا بعداً پخش شود.',
      'تصویر / PDF', 'دعوت‌نامه یا سند', 'عکس دعوت‌نامه یا سند PDF پیوست کن، برای قرارها و مناسبت‌ها مفید است.',
      'مکان', 'لینک نقشه یا انتخاب نقطه', 'لینک گوگل‌مپ را بچسبان یا نقطه‌ای انتخاب کن، سپس هنگام زنگ برای مسیر بازش کن.',
      'پیش‌نمایش زنده', 'هنگام نوشتن ببین', 'ببین یادآور هنگام نوشتن دقیقاً چگونه دیده و خوانده می‌شود.'],
    ['نمایش و سازمان‌دهی',
      'فهرست یا شبکه', 'انتخابت ذخیره می‌شود', 'با دکمه نوار بالا بین فهرست و شبکه کارت‌ها جابه‌جا شو؛ انتخابت به یاد سپرده می‌شود.',
      'گروه‌های زمانی رنگی', 'امروز / فردا / این هفته / بعداً', 'یادآورها بر اساس زمان زنگ گروه‌بندی و رنگی می‌شوند: امروز، فردا، این هفته و بعداً.',
      'جستجو', 'هر یادآور را سریع پیدا کن', 'آیکن جستجو را بزن و واژه‌ای تایپ کن تا یادآور را فوری بیابی.',
      'قالب‌ها', 'یادآورهای آماده', 'قالب‌ها را باز کن تا با یک ضربه از یادآور آماده (دارو، سفر، خودرو، قبض و…) شروع کنی.',
      'ساخت صوتی', 'بگو؛ فرم پر می‌شود', 'جمله‌ای طبیعی بگو و فرم خودش پر می‌شود تا تأیید کنی.'],
    ['بینش‌ها',
      'تابلوی امروز', 'سررسید، بحرانی، معوق، فعال + بعدی', 'تابلویی که سررسید امروز، بحرانی، معوق و فعال را نشان می‌دهد، به‌علاوه زنگ بعدی.',
      'آمار', 'مجموع‌ها و الگوها', 'مجموع، شمار این هفته، پرکارترین ساعت و پرتکرارترین یادآورت را ببین.',
      'گزارش اعلان‌ها', 'خودکار ثبت می‌شود', 'هر یادآور اجراشده خودکار در گزارش ثبت می‌شود تا گذشته را مرور کنی.'],
    ['سیستم و تنظیمات',
      'به‌روزرسانی درون‌برنامه', 'بدون مرورگر', 'تنظیمات ← درباره و کمک ← بررسی به‌روزرسانی را باز کن؛ برنامه خودش نسخه جدید را دانلود و نصب می‌کند.',
      'پشتیبان', 'ذخیره و بازیابی', 'در تنظیمات ← امنیت و پشتیبان، یک پشتیبان رمزنگاری‌شده ذخیره کن و بعداً روی هر دستگاهی بازیابی کن.',
      'همگام‌سازی ابری', 'گوگل‌درایو رمزنگاری‌شده', 'در صفحه پشتیبان گوگل‌درایو را انتخاب کن، وارد شو، روی هر دستگاه همان عبارت رمز را بگذار، و همگام‌سازی خودکار را روشن کن؛ داده پیش از ارسال رمزنگاری می‌شود.',
      'قفل برنامه', 'پین یا اثر انگشت', 'برنامه را با پین یا اثر انگشت از تنظیمات ← امنیت و پشتیبان محافظت کن.',
      'افزودن به تقویم', 'خروجی .ics یا اشتراک', 'یک یادآور را به‌صورت فایل .ics خروجی بگیر تا به تقویم گوشی افزوده شود، یا به‌صورت متن به اشتراک بگذار.',
      'فعال‌سازی', 'کلید مجوز عالمی', 'کلید مجوز عالمی را یک بار برای فعال‌سازی وارد کن؛ بعداً می‌توانی برای آزمایش روی دستگاه دیگر غیرفعالش کنی.'],
  ],
  'ru': [
    ['Быстрый старт',
      'Нажмите +', 'Открывает лист нового напоминания', 'Кнопка + внизу открывает лист нового напоминания, где всё настраивается в одном месте.',
      'Заголовок', 'Что напомнить — или продиктуйте', 'Введите задачу или нажмите микрофон в поле заголовка, чтобы продиктовать её.',
      'Выберите время', 'Дата и время, хиджра или григориан', 'Задайте дату и время; переключайтесь между хиджрой и григорианом кнопкой календаря в выборе.',
      'Сохранить', 'Сразу планируется', 'Нажмите Сохранить, и напоминание сразу планируется и появляется на Главной в своей временной группе.',
      'Голосом', 'Скажите фразу на Главной', 'Нажмите маленький микрофон на Главной и скажите целую фразу; время и задача заполнятся для подтверждения.'],
    ['Типы напоминаний',
      'Общее', 'Любое повседневное', 'Тип по умолчанию для любой повседневной задачи без особой категории.',
      'Лекарство', 'Дозы и счёт курса', 'Добавляет поле дозы и необязательный счёт курса, чтобы приложение отслеживало остаток доз.',
      'Встреча', 'С местом и приглашением', 'Позволяет прикрепить место на карте (ссылка Google Maps) и приглашение картинкой или PDF.',
      'Событие', 'Дни рождения и события — ежегодно', 'Лучше для дней рождения и ежегодных событий; по умолчанию ежегодный повтор.',
      'Счета', 'Повторяющиеся платежи', 'Для повторяющихся платежей; сочетайте с ежемесячным повтором для каждого цикла.',
      'Поездка', 'Поездки и вылеты', 'Для поездок и вылетов; добавьте предупреждение, чтобы выехать вовремя.',
      'Машина', 'Обслуживание и продления', 'Для дат ТО и продления документов; используйте ежегодный или свой повтор.'],
    ['Время и повтор',
      'Повтор', 'Раз · ежедневно · еженедельно · ежемесячно · ежегодно', 'Выберите Раз, Ежедневно, Еженедельно (выберите дни), Ежемесячно или Ежегодно в селекторе.',
      'Ежегодно хиджра', 'По дате хиджры каждый год', 'Повторяется в ту же дату хиджры (лунную) каждый год, идеально для исламских событий.',
      'Каждые N дней', 'Свой интервал', 'Выберите свой интервал, например каждые 3 или 10 дней, когда стандартные повторы не подходят.',
      'Курс лекарства', 'Остаток убывает', 'Задайте общее число доз; остаток убывает с каждым запланированным временем.',
      'Предупредить заранее', '5 мин / 15 мин / час / день до', 'Получите раннее предупреждение за 5 мин, 15 мин, час или день до настоящего времени.',
      'Отложить', '5–60 минут с будильника', 'Когда будильник звонит, отложите его на 5–60 минут с экрана будильника.'],
    ['Звук и срочность',
      'Библиотека звуков', 'Встроенные и звуки устройства', 'Выберите встроенные сигналы, мягкие звуки природы или любой сигнал на устройстве, включая Huawei.',
      'Повышать громкость', 'Слышно в тихом/тихо', 'Включите, чтобы будильник сам повышал громкость и был слышен даже в тихом режиме.',
      'Растущая критичность', 'Растёт при игнорировании', 'Для критических напоминаний звук и вибрация растут каждые несколько секунд, пока вы не ответите.',
      'Режим без промаха', 'Решите пример перед закрытием', 'Включите, чтобы решить небольшой пример, прежде чем закрыть будильник.',
      'Надёжный будильник', 'Закрытым, после перезагрузки, на весь экран', 'Будильник срабатывает даже при закрытом приложении или после перезагрузки, на весь экран и офлайн.'],
    ['Настройка и вложения',
      'Свой цвет', 'Виден на карточке', 'Выберите цвет из палитры; он виден на карточке, чтобы узнать её с первого взгляда.',
      'Важность', 'Обычное или критический будильник', 'Поставьте Обычное для тихого уведомления или Критическое, чтобы открыть полноэкранный будильник со звуком и вибрацией.',
      'Голосовая заметка', 'Прикрепить запись', 'Запишите короткую голосовую заметку и прикрепите к напоминанию для прослушивания позже.',
      'Изображение / PDF', 'Приглашение или документ', 'Прикрепите фото приглашения или документ PDF, удобно для встреч и событий.',
      'Место', 'Ссылка карты или выбор точки', 'Вставьте ссылку Google Maps или выберите точку, затем откройте для маршрута, когда сработает напоминание.',
      'Живой просмотр', 'Видите при наборе', 'Видите, как именно выглядит и читается напоминание, пока его набираете.'],
    ['Вид и порядок',
      'Список или сетка', 'Выбор сохраняется', 'Переключайте список и сетку карточек кнопкой верхней панели; выбор запоминается.',
      'Цветные группы по времени', 'Сегодня / завтра / на неделе / позже', 'Напоминания сгруппированы и окрашены по времени: сегодня, завтра, на этой неделе и позже.',
      'Поиск', 'Быстро найти напоминание', 'Нажмите поиск и введите слово, чтобы мгновенно найти напоминание.',
      'Шаблоны', 'Готовые напоминания', 'Откройте шаблоны, чтобы одним касанием начать с готового напоминания (лекарство, поездка, машина, счёт и др.).',
      'Создать голосом', 'Скажите; форма заполнится', 'Скажите естественную фразу, и форма заполнится сама для подтверждения.'],
    ['Аналитика',
      'Доска на сегодня', 'К сроку, критич., просроч., активн. + следующее', 'Доска показывает, что к сроку сегодня, что критично, просрочено и активно, плюс следующий будильник.',
      'Статистика', 'Итоги и закономерности', 'Смотрите итоги, счёт за неделю, ваш самый занятой час и самое частое напоминание.',
      'Журнал уведомлений', 'Записывается сам', 'Каждое сработавшее напоминание записывается автоматически, чтобы вы пересмотрели прошедшее.'],
    ['Система и настройки',
      'Обновление в приложении', 'Без браузера', 'Откройте Настройки → О приложении и помощь → Проверить обновления; приложение само скачивает и устанавливает новую версию.',
      'Резервная копия', 'Сохранить и восстановить', 'В Настройки → Безопасность и копия сохраните зашифрованную копию и восстановите её позже на любом устройстве.',
      'Облачная синхронизация', 'Шифрованный Google Drive', 'На экране копии выберите Google Drive, войдите, задайте одну и ту же парольную фразу на каждом устройстве и включите автосинхронизацию; данные шифруются до отправки.',
      'Блокировка', 'PIN или отпечаток', 'Защитите приложение PIN-кодом или отпечатком в Настройки → Безопасность и копия.',
      'В календарь', 'Экспорт .ics или поделиться', 'Экспортируйте напоминание в файл .ics для календаря телефона или поделитесь им как текстом.',
      'Активация', 'Универсальный лицензионный ключ', 'Введите универсальный лицензионный ключ один раз для активации; позже можно деактивировать для проверки на другом устройстве.'],
  ],
  'tr': [
    ['Hızlı başlangıç',
      '+ öğesine dokunun', 'Yeni hatırlatıcı sayfasını açar', 'Alttaki + düğmesi, her şeyi tek yerde ayarladığın yeni hatırlatıcı sayfasını açar.',
      'Başlık', 'Ne hatırlatılacak — ya da söyle', 'Görevi yaz veya başlık alanındaki mikrofona dokunup söyle.',
      'Zamanı seçin', 'Tarih ve saat, Hicri veya Miladi', 'Tarih ve saati ayarla; seçicideki takvim düğmesiyle Hicri ile Miladi arasında geç.',
      'Kaydet', 'Anında planlanır', 'Kaydet düğmesine dokun, hatırlatıcı hemen planlanır ve Ana ekranda zaman grubunda görünür.',
      'Sesle ekle', 'Ana ekranda bir cümle söyle', 'Ana ekrandaki küçük mikrofona dokun ve tam bir cümle söyle; zaman ve görev onaylaman için doldurulur.'],
    ['Hatırlatıcı türleri',
      'Genel', 'Her türlü günlük hatırlatıcı', 'Özel bir kategoriye girmeyen her günlük görev için varsayılan tür.',
      'İlaç', 'Dozlar ve kür sayımı', 'Bir doz alanı ve isteğe bağlı kür sayımı ekler, böylece uygulama kalan dozu izler.',
      'Randevu', 'Konum ve davetiyeyle', 'Harita konumu (Google Haritalar bağlantısı) ve resim veya PDF davetiyesi eklemeyi sağlar.',
      'Özel gün', 'Doğum günleri ve etkinlikler — yıllık', 'Doğum günleri ve yıllık etkinlikler için idealdir; varsayılan olarak yıllık tekrar.',
      'Faturalar', 'Yinelenen ödemeler', 'Yinelenen ödemeler için; her dönem hatırlatmak üzere aylık tekrarla eşle.',
      'Seyahat', 'Yolculuklar ve kalkışlar', 'Yolculuklar ve kalkışlar için; zamanında çıkmak üzere bir ön uyarı ekle.',
      'Araba', 'Bakım ve yenilemeler', 'Bakım tarihleri ve belge yenilemeleri için; yıllık veya özel tekrar kullan.'],
    ['Zaman ve tekrar',
      'Tekrar', 'Bir kez · günlük · haftalık · aylık · yıllık', 'Seçiciden Bir kez, Günlük, Haftalık (günleri seç), Aylık veya Yıllık seç.',
      'Yıllık Hicri', 'Her yıl Hicri tarihte', 'Her yıl aynı Hicri (ay) tarihte tekrarlanır, İslami günler için idealdir.',
      'Her N günde', 'Kendi özel aralığın', 'Standart tekrarlar uymadığında her 3 veya 10 gün gibi kendi aralığını seç.',
      'İlaç küründe', 'Kalan azalır', 'Toplam doz sayısını belirle; kalan, her planlanan zamanda azalır.',
      'Ön uyarı', '5 dk / 15 dk / saat / gün önce', 'Gerçek zamandan 5 dk, 15 dk, bir saat veya bir gün önce erken uyarı al.',
      'Erteleme', 'Alarm ekranından 5–60 dakika', 'Alarm çaldığında alarm ekranından 5 ila 60 dakika ertele.'],
    ['Ses ve aciliyet',
      'Ses kütüphanesi', 'Yerleşik ve cihaz tonları', 'Yerleşik tonları, yumuşak doğa seslerini veya cihazındaki herhangi bir tonu (Huawei dahil) seç.',
      'Sesi yükselt', 'Sessiz/kısıkta duyulur', 'Aç ki alarm sesi kendi yükseltsin ve telefon sessiz veya kısık olsa bile duyulsun.',
      'Artan kritik', 'Yok sayılırsa artar', 'Kritik hatırlatıcılarda ses ve titreşim, yanıt verene kadar birkaç saniyede bir artar.',
      'Kaçırılmaz mod', 'Kapatmadan önce toplama çöz', 'Aç ki alarm kapatılabilmeden önce küçük bir toplama çözmen gereksin.',
      'Güvenilir alarm', 'Kapalı, yeniden başlatma sonrası, tam ekran', 'Alarm uygulama kapalıyken veya yeniden başlatmadan sonra bile çalar, tam ekran ve çevrimdışı.'],
    ['Özelleştir ve ekle',
      'Özel renk', 'Kartta görünür', 'Paletten bir renk seç; bir bakışta tanıman için kartta görünür.',
      'Önem', 'Normal veya kritik alarm', 'Sessiz bildirim için Normal, sesli ve titreşimli tam ekran alarm için Kritik seç.',
      'Sesli not', 'Bir kayıt ekle', 'Kısa bir sesli not kaydet ve sonra çalmak için hatırlatıcıya ekle.',
      'Resim / PDF', 'Davetiye veya belge', 'Davetiye fotoğrafı veya PDF belge ekle, randevu ve etkinlikler için kullanışlı.',
      'Konum', 'Harita bağlantısı veya nokta seç', 'Google Haritalar bağlantısı yapıştır veya nokta seç, sonra alarm çaldığında yön için aç.',
      'Canlı önizleme', 'Yazarken gör', 'Hatırlatıcıyı yazarken tam olarak nasıl görüneceğini ve okunacağını gör.'],
    ['Görünüm ve düzen',
      'Liste veya ızgara', 'Seçimin kaydedilir', 'Üst çubuk düğmesiyle liste ve kart ızgarası arasında geç; seçimin hatırlanır.',
      'Renkli zaman grupları', 'Bugün / yarın / bu hafta / sonra', 'Hatırlatıcılar zamanına göre gruplanır ve renklenir: bugün, yarın, bu hafta ve sonra.',
      'Ara', 'Hatırlatıcıyı hızlı bul', 'Arama simgesine dokun ve bir kelime yaz, hatırlatıcıyı anında bul.',
      'Şablonlar', 'Hazır hatırlatıcılar', 'Tek dokunuşla hazır bir hatırlatıcıdan (ilaç, seyahat, araba, fatura vb.) başlamak için şablonları aç.',
      'Sesle oluşturma', 'Söyle; form dolar', 'Doğal bir cümle söyle, form onaylaman için kendini doldurur.'],
    ['Analizler',
      'Bugün panosu', 'Zamanı gelen, kritik, gecikmiş, etkin + sonraki', 'Bugün zamanı geleni, kritiği, gecikmişi ve etkini gösteren bir pano, ayrıca sonraki alarm.',
      'İstatistikler', 'Toplamlar ve örüntüler', 'Toplamları, bu hafta sayısını, en yoğun saatini ve en sık hatırlatıcını gör.',
      'Bildirim kaydı', 'Otomatik kaydedilir', 'Çalan her hatırlatıcı otomatik kaydedilir, böylece geçmişi gözden geçirebilirsin.'],
    ['Sistem ve ayarlar',
      'Uygulama içi güncelleme', 'Tarayıcı gerekmez', 'Ayarlar → Hakkında ve yardım → Güncellemeleri denetle aç; uygulama yeni sürümü kendi indirip kurar.',
      'Yedekleme', 'Kaydet ve geri yükle', 'Ayarlar → Güvenlik ve yedek bölümünde şifreli bir yedek kaydet ve sonra herhangi bir cihazda geri yükle.',
      'Bulut eşitleme', 'Şifreli Google Drive', 'Yedek ekranında Google Drive seç, oturum aç, her cihazda aynı şifreleme parolasını ayarla ve otomatik eşitlemeyi aç; veriler telefondan çıkmadan şifrelenir.',
      'Uygulama kilidi', 'PIN veya parmak izi', 'Uygulamayı Ayarlar → Güvenlik ve yedek bölümünden PIN veya parmak iziyle koru.',
      'Takvime ekle', '.ics dışa aktar veya paylaş', 'Bir hatırlatıcıyı telefon takvimine eklemek için .ics dosyası olarak dışa aktar veya metin olarak paylaş.',
      'Etkinleştirme', 'Evrensel lisans anahtarı', 'Etkinleştirmek için evrensel lisans anahtarını bir kez gir; sonra başka cihazda denemek için devre dışı bırakabilirsin.'],
  ],
};

const Map<String, HgChrome> _hgChrome = {
  'en': HgChrome('Every feature — clearly explained', 'items', 'Updated: 2026-06-28'),
  'ar': HgChrome('كلّ ميزة — مشروحة بوضوح', 'عنصر', 'آخر تحديث: 2026-06-28'),
  'es': HgChrome('Cada función, explicada con claridad', 'elementos', 'Actualizado: 2026-06-28'),
  'de': HgChrome('Jede Funktion — klar erklärt', 'Einträge', 'Aktualisiert: 2026-06-28'),
  'fil': HgChrome('Bawat feature — malinaw na ipinaliwanag', 'item', 'Na-update: 2026-06-28'),
  'fr': HgChrome('Chaque fonction — clairement expliquée', 'éléments', 'Mis à jour : 2026-06-28'),
  'id': HgChrome('Setiap fitur — dijelaskan dengan jelas', 'item', 'Diperbarui: 2026-06-28'),
  'it': HgChrome('Ogni funzione — spiegata con chiarezza', 'elementi', 'Aggiornato: 2026-06-28'),
  'ms': HgChrome('Setiap ciri — diterang dengan jelas', 'item', 'Dikemas kini: 2026-06-28'),
  'hi': HgChrome('हर सुविधा — स्पष्ट रूप से समझाई गई', 'आइटम', 'अपडेट: 2026-06-28'),
  'bn': HgChrome('প্রতিটি ফিচার — স্পষ্টভাবে ব্যাখ্যা', 'আইটেম', 'আপডেট: 2026-06-28'),
  'fa': HgChrome('هر قابلیت — شفاف توضیح داده‌شده', 'مورد', 'به‌روزرسانی: 2026-06-28'),
  'ru': HgChrome('Каждая функция — понятно объяснена', 'элементов', 'Обновлено: 2026-06-28'),
  'tr': HgChrome('Her özellik — açıkça anlatıldı', 'öğe', 'Güncellendi: 2026-06-28'),
};

List<HgSection> helpSections(String lang) => _build(_hg[lang] ?? _hg['en']!);
HgChrome helpChrome(String lang) => _hgChrome[lang] ?? _hgChrome['en']!;
